### ISSUE TITLE
rds optioin group module should support definition of IAM role with the options, SQLSERVER_BACKUP_RESTORE

### ISSUE THREAD

**Issue by joonhuang** [ansible-collections/community.aws#1003]
### Summary

Current rds_option_group module doesn't support definition of IAM role when option is SQLSERVER_BACKUP_RESTORE and hitting error from AWS saying IAM role is required

### Issue Type

Feature Idea

### Component Name

rds_option_group

### Additional Information

```
rds_option_group:
    state: present
    region: ap-south-1
    option_group_name: "{{ project_name }}-sqlserver-ex"
    engine_name: sqlserver-ex
    major_engine_version: "15.00"
    option_group_description: "Microsoft SQL Server Express Option Group"
    option: SQLSERVER_BACKUP_RESTORE
    s3_iam_role_arn: xxxxxx
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
