### ISSUE TITLE
rds_instance - Broken check_mode and idempotence

### ISSUE THREAD

**Issue by jatorcasso** [ansible-collections/community.aws#1013]
### Summary

When adding integration tests for adding iam_roles support for rds_instance, I noticed check_mode tests fail on idempotence checks, as well as some other checks like adding sgs on check_mode, etc.

### Issue Type

Bug Report

### Component Name

rds_instance

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
    - name: Create DB instance with IAM roles (idempotence) - check_mode
      rds_instance:
        id: "{{ instance_id }}"
        state: present
        engine: postgres
        engine_version: "{{ postgres_db_engine_version }}"
        username: "{{ username }}"
        password: "{{ password }}"
        db_instance_class: "{{ postgres_db_instance_class }}"
        allocated_storage: "{{ allocated_storage }}"
        allow_major_version_upgrade: yes
        iam_roles:
          - role_arn: "{{ s3_integration_role_1.arn }}"
            feature_name: 's3Export'
          - role_arn: "{{ s3_integration_role_2.arn }}"
            feature_name: 'Lambda'
          - role_arn: "{{ s3_integration_role_3.arn }}"
            feature_name: 's3Import'
      register: result
      check_mode: yes

    - assert:
        that:
          - not result.changed
```

### Expected Results

expected check_mode to not modify anything and return the correct `changed`

### Actual Results

in idempotence tests, check_mode returned `changed = True`. When adding sg on check_mode, the sgs were actually added.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
