### ISSUE TITLE
SNS Topic Subscription filter_policy

### ISSUE THREAD

**Issue by citrocity** [ansible-collections/community.aws#1088]
### Summary

Similar issue was opened in the old project by @bcarpio https://github.com/ansible/ansible/issues/51756 but was closed due to the migration of the project.

SNS Topic (sns_topic) in Ansible supports subscriptions but it doesn't seem to support subscription filter_policies.

https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html

### Issue Type

Feature Idea

### Component Name

community.aws.sns_topic

### Additional Information

This feature is important so messages sent to the SNS topic subscriber (Lambda, SQS, etc..) are filtered at the AWS level before it reaches the code or queue subscribed to the topic.
```
  subscriptions:
    - endpoint: "{{ aws_lambda_result.configuration.function_arn}}"
       protocol: lambda
       filter_policy:
         attribute_a:
           - value_1
           - value_2
         attribute_b:
           - value_3
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
