### ISSUE TITLE
community.aws.elb_target_module.rst Documentation Issue

### ISSUE THREAD

**Issue by AaronJaegerVA** [ansible-collections/community.aws#1140]
### Summary

I was reading https://github.com/ansible-collections/community.aws/blob/main/docs/community.aws.elb_target_module.rst and saw this in the Examples section:

```
- name: Register an IP address target to a target group
  community.aws.elb_target:
    target_group_name: myiptargetgroup
    target_id: i-1234567
    state: present
```

I believe `target_id` should be followed by some mock IP address instead of an EC2 instance ID.

### Issue Type

Documentation Report

### Component Name

community.aws.elb_target_module.rst

### Ansible Version

N/A Documentation Issue

### Collection Versions

N/A Documentation Issue

### Configuration

N/A Documentation Issue

### OS / Environment

N/A Documentation Issue

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
