### ISSUE TITLE
lambda_info - only queries config info when function_name is omitted

### ISSUE THREAD

**Issue by jatorcasso** [ansible-collections/community.aws#1151]
### Summary

When trying to retrieve info on all lambda functions (by omitting `function_name`), module acts as if `query = config`

### Issue Type

Bug Report

### Component Name

lambda_info

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
  # Query the Lambda
  - name: lambda_info | Gather all infos for all lambda functions
    lambda_info:
    register: lambda_infos_all
    check_mode: yes
  - name: lambda_info | Assert successfull retrieval of all information
    assert:
      that:
      - lambda_infos_all | length > 0
      - lambda_infos_all is not failed
      - lambda_infos_all.function[lambda_function_name].function_name == lambda_function_name
      - lambda_infos_all.function[lambda_function_name].runtime == "python3.6"
      - lambda_infos_all.function[lambda_function_name].versions is defined
      - lambda_infos_all.function[lambda_function_name].aliases is defined
      - lambda_infos_all.function[lambda_function_name].policy is defined
      - lambda_infos_all.function[lambda_function_name].mappings is defined
      - lambda_infos_all.function[lambda_function_name].description == ""
      - lambda_infos_all.function[lambda_function_name].function_arn is defined
      - lambda_infos_all.function[lambda_function_name].handler == "mini_lambda.handler"
      - lambda_infos_all.function[lambda_function_name].tags is defined
```

### Expected Results

```yaml (paste below)
"function": {
        "70f9dc46f894": {
            "aliases": [],
            "code_sha256": "LC/DkOB9wKYLWMSMqYoGPw8yyXUVHcDcdShg/MUKyYM=",
            "code_size": 854,
            "description": "",
            "function_arn": "arn:aws:lambda:us-east-1:721066863947:function:70f9dc46f894",
            "function_name": "70f9dc46f894",
            "handler": "mini_lambda.handler",
            "last_modified": "2022-05-19T19:46:15.375+0000",
            "mappings": [],
            "memory_size": 128,
            "package_type": "Zip",
            "policy": {},
            "response_metadata": {
                "http_headers": {
                    "connection": "keep-alive",
                    "content-length": "986",
                    "content-type": "application/json",
                    "date": "Thu, 19 May 2022 19:46:18 GMT",
                    "x-amzn-requestid": "0b50adea-e1ed-4f25-975f-f0eec9478282"
                },
                "http_status_code": 200,
                "request_id": "0b50adea-e1ed-4f25-975f-f0eec9478282",
                "retry_attempts": 0
            },
            "revision_id": "20bbfe78-8589-46ca-8fb3-6ff089ea7bab",
            "role": "arn:aws:iam::721066863947:role/ansible-test-70f9dc46f894-lambda",
            "runtime": "python3.6",
            "state": "Pending",
            "state_reason": "The function is being created.",
            "state_reason_code": "Creating",
            "tags": {},
            "timeout": 3,
            "tracing_config": {
                "mode": "PassThrough"
            },
            "version": "$LATEST",
            "versions": [
                {
                    "code_sha256": "LC/DkOB9wKYLWMSMqYoGPw8yyXUVHcDcdShg/MUKyYM=",
                    "code_size": 854,
                    "description": "",
                    "function_arn": "arn:aws:lambda:us-east-1:721066863947:function:70f9dc46f894:$LATEST",
                    "function_name": "70f9dc46f894",
                    "handler": "mini_lambda.handler",
                    "last_modified": "2022-05-19T19:46:15.375+0000",
                    "memory_size": 128,
                    "package_type": "Zip",
                    "revision_id": "20bbfe78-8589-46ca-8fb3-6ff089ea7bab",
                    "role": "arn:aws:iam::721066863947:role/ansible-test-70f9dc46f894-lambda",
                    "runtime": "python3.6",
                    "timeout": 3,
                    "tracing_config": {
                        "mode": "PassThrough"
                    },
                    "version": "$LATEST"
                },
                {
                    "code_sha256": "LC/DkOB9wKYLWMSMqYoGPw8yyXUVHcDcdShg/MUKyYM=",
                    "code_size": 854,
                    "description": "",
                    "function_arn": "arn:aws:lambda:us-east-1:721066863947:function:70f9dc46f894:1",
                    "function_name": "70f9dc46f894",
                    "handler": "mini_lambda.handler",
                    "last_modified": "2022-05-19T19:46:15.375+0000",
                    "memory_size": 128,
                    "package_type": "Zip",
                    "revision_id": "23d33d24-983b-47e2-92cd-142bc18b1833",
                    "role": "arn:aws:iam::721066863947:role/ansible-test-70f9dc46f894-lambda",
                    "runtime": "python3.6",
                    "timeout": 3,
                    "tracing_config": {
                        "mode": "PassThrough"
                    },
                    "version": "1"
                }
            ]
        }
```

### Actual Results

```yaml (paste below)
    "function": {
        "7a603343767f": {
            "code_sha256": "HcAK+Oux100a8L18ww1SdRC1NgwU4CTn0RHIj65dHO4=",
            "code_size": 854,
            "description": "",
            "function_arn": "arn:aws:lambda:us-east-1:721066863947:function:7a603343767f",
            "function_name": "7a603343767f",
            "handler": "mini_lambda.handler",
            "last_modified": "2022-05-19T19:59:25.000+0000",
            "memory_size": 128,
            "package_type": "Zip",
            "revision_id": "d1d89e30-797d-453f-92ae-efc1f6ab7c34",
            "role": "arn:aws:iam::721066863947:role/ansible-test-7a603343767f-lambda",
            "runtime": "python3.6",
            "tags": {
                "camel_case": "ACamelCaseValue",
                "snake_case": "a_snake_case_value",
                "spaced key": "A value with spaces"
            },
            "timeout": 3,
            "tracing_config": {
                "mode": "PassThrough"
            },
            "version": "$LATEST"
        }
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
