### ISSUE TITLE
community.aws.elb_target Draining Targets Unexpectedly

### ISSUE THREAD

**Issue by AaronJaegerVA** [ansible-collections/community.aws#1194]
### Summary

When I run community.aws.elb_target to add targets to an existing target group, it works well; however, when I run the same job again, the targets I request are drained instead of being left alone. I'm not sure how to debug this.

### Issue Type

Bug Report

### Component Name

elb_target

### Ansible Version

```
bash-4.4# ansible --version
/usr/local/lib/python3.8/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible [core 2.13.0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True
```

### Collection Versions

```
# /usr/share/ansible/collections/ansible_collections
Collection         Version
------------------ -------
amazon.aws         3.2.0  
ansible.controller 4.1.2  
community.aws      3.2.1  
kubernetes.core    2.2.3  
redhat.openshift   2.1.0
```

### AWS SDK versions

```console (paste below)
bash-4.4# pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /usr/local/lib/python3.8/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.23.9
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.8/site-packages
Requires: botocore, jmespath, s3transfer
Required-by: 
---
Name: botocore
Version: 1.26.9
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.8/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer```


### Configuration

```console (paste below)
$ ansible-config dump --only-changed
(no output)
```

### OS / Environment

RHEL8 UBI EE

### Steps to Reproduce

```yaml (paste below)
- name: Register instance target(s) to {{ use_environment }}-iris-mail-tgrp target group
  community.aws.elb_target:
    aws_access_key: "{{ cred_aws_access_key }}"
    aws_secret_key: "{{ cred_aws_secret_key }}"
    region: "{{ aws_region }}"
    target_group_name: "{{ use_environment }}-iris-mail-tgrp"
    target_id: "{{ item.instances[0].instance_id }}"
    target_port: "{{ scm_iris_mail_target_port }}"
    state: present
    debug_botocore_endpoint_logs: true
  loop: "{{ worker_instances.results }}"
```

### Expected Results

I expect targets that already exist to be left alone.

### Actual Results

Existing targets go into "draining" status and eventually disappear.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
