### ISSUE TITLE
Add launchTemplate support to batch compute environment creation

### ISSUE THREAD

**Issue by FrBonnardel** [ansible-collections/community.aws#1347]
### Summary

Add launchTemplate support to batch compute environment creation

### Issue Type

Feature Idea

### Component Name

batch compute environment
https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/batch_compute_environment.py

### Additional Information

```yaml (paste below)

  launchTemplate:
    description:
      - launch template to use to deploy the compute environment. arn 
        launchTemplate:{"launchTemplateName": "mytemplate_lt","version": "$Default"}

In creation:
    compute_resources_param_list = ('minv_cpus', 'maxv_cpus', 'desiredv_cpus', 'instance_types', 'image_id', 'subnets',
                                    'security_group_ids', 'ec2_key_pair', 'instance_role', 'tags', 'bid_percentage',
                                    'spot_iam_fleet_role', 'launchTemplate')

in Main:
        launchTemplate=dict(type='dict'),
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
