### ISSUE TITLE
cloudwatchevent_rule doesn't support JSON input_templates

### ISSUE THREAD

**Issue by alalonde** [ansible-collections/community.aws#1348]
### Summary

AWS EventBridge supports JSON for their input templates. However, we are assuming a string is desired, and therefore wrap the input template in quotes, which is not parsed by AWS as a JSON template.

### Issue Type

Bug Report

### Component Name

cloudwatchevent_rule

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

This was pointing to master. From our Dockerfile:
```console 
RUN ansible-galaxy collection install git+https://github.com/ansible-collections/community.aws.git,main
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

Here is a working example using the AWS CLI:

```
eventbridge_target.json
{
   "Rule": "myRule",
   "Targets": [{
      ...
      "InputTransformer": {
         "InputPathsMap": {
            "s3Key": "$.detail.object.key"
         },
         "InputTemplate": "{\"containerOverrides\": [{\"name\": \"thrivSportsJob-stage_jobmg10\", \"environment\": [{\"name\": \"S3_KEY\",\"value\": <s3Key>}]}]}"
      }
   }]
}
```

Which can be executed with a `aws events put-targets --cli-input-json file://eventbridge_target.json`

However, when parsing the target configuration, the input is wrapped in a string:
```
                target_request['InputTransformer']['InputTemplate'] = '"{0}"'.format(
                    target['input_template']
                )
```

AWS will not route an event with an invalid transformer template. So the input for a JSON template must begin with a `{`, not a `"`. My [solution](https://github.com/alalonde/community.aws/commit/33e57f964687c09e81de238f936fc5b63f95bd76) was to remove the string wrapping, AND prepend the template with a space, as [recommended here](https://stackoverflow.com/a/32014283/331791). This results in:

```yaml
      -  name: Define trigger input template
         set_fact:
            trigger_input_template: |
               {
                  "containerOverrides": [{
                     "name": "{{container_name}}",
                     "environment": [{
                        "name": "S3_KEY",
                        "value": <s3Key>
                     }]
                  }]
               }
      -  name: Create rule in EventBridge
         community.aws.cloudwatchevent_rule:
            ...
            targets:
               -  id: "myJob-{{env}}"
                  ...
                  input_paths_map:
                     s3Key: "$.detail.object.key"
                  input_template: " {{trigger_input_template}}"
                  ...
```

### Expected Results

I expected the input template to be wrapped by `{ ... }` but was instead `"{ ... }"`

![image](https://user-images.githubusercontent.com/1402582/178361885-d1ad3ff8-3071-4316-b6c0-822e629a07c9.png)

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
