### ISSUE TITLE
add support for gp3 volume throughput setting in ec2_instance

### ISSUE THREAD

**Issue by sugymt** [ansible-collections/community.aws#1416]
### Summary

The ec2_instance module doesn't seem to support the `throughput` parameter for `gp3` volume types. This parameter is supported by `amazon.aws.ec2_vol` and `amazon.aws.ec2_lc`.

Related to #784

### Issue Type

Feature Idea

### Component Name

ec2_instance

### Additional Information

```yaml (paste below)
- amazon.aws.ec2:
    key_name: mykey
    group: webserver
    instance_type: c3.medium
    image: ami-123456
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/xvda
        volume_type: gp3
        volume_size: 8
        throughput: 250
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: yes
    count_tag:
      Name: dbserver
    exact_count: 1
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by markuman** [comment]
The `ec2_instance` module has moved to [`amazon.aws`](https://github.com/ansible-collections/amazon.aws) collection.  
And your example is refering to `amazon.aws.ec2` module that is deprecated and I think does not exists anymore already.

However, the `throughput` parameter is supported and works for `amazon.aws.ec2_instance` module.

```
$ ansible-galaxy collection list |grep aws
amazon.aws         4.1.0   
community.aws      4.1.1
```

```yml
---
- hosts: localhost

  tasks:
    - name: create instance
      amazon.aws.ec2_instance:
        launch_template:
          name: ubuntu-22.04
        instance_type: t3a.nano
        vpc_subnet_id: subnet-c14a06a3
        name: test-1416
        instance_role: ec2_base
        termination_protection: no
        security_groups:
          - linux_base
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 8
              volume_type: gp3
              iops: 3000
              throughput: 125
              delete_on_termination: true
          - device_name: /dev/sdb
            ebs:
              volume_size: 500
              volume_type: gp3
              iops: 3000
              throughput: 150
              delete_on_termination: true
```
