### ISSUE TITLE
How to pass firelensConfiguration to an ecs_taskdefinition?

### ISSUE THREAD

**Issue by threewordphrase** [ansible-collections/community.aws#1425]
### Summary

I am trying to use the ecs_taskdefinition module to replicate a fluentd logging setup I currently have in production. I see where all of the options I need are, except I do not see how I can set `firelensConfiguration` on my fluentd sidecar container. Here is the JSON for my taskdefinition.

```
"cpu": ...,
"memory": ...,
"firelensConfiguration": {
        "type": "fluentd",
        "options": {
          "config-file-type": "file",
          "enable-ecs-log-metadata": "true",
          "config-file-value": "/fluentd/etc/fluent.conf"
        }
      },
```

How can I do this with the ansible module?

### Issue Type

Documentation Report

### Component Name

ecs_taskdefinition

### Ansible Version

2.9

### OS / Environment

debian

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/ecs_taskdefinition.py`](https://github.com/['ansible-collections/amazon.aws', 'ansible-collections/community.aws', 'ansible-collections/community.vmware']/blob/main/plugins/modules/ecs_taskdefinition.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Java1Guy @alinabuzachis @jillr @markuman @s-hertel @tremble
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alinabuzachis** [comment]
@threewordphrase Thank you for raising this. Unfortunately, this option doesn't seem to be document. However, it should work if you specify it as a suboption of containers, something like this:

```
- name: Create task definition
  community.aws.ecs_taskdefinition:
    family: nginx
    containers:
    - name: '...'
      essential: true
      image: "..."
      portMappings:
      - containerPort: 8080
         hostPort: 8080
      cpu: 512
      memory: 1024
      firelensConfiguration:
        type: "fluentd"
        options:
          "config-file-type": "file"
          "enable-ecs-log-metadata": "true"
          "config-file-value": "/fluentd/etc/fluent.conf"
```

Can you please try it and let us know? Would you be interested opening a pull request to update the module's documentation or add any patch wether necessary?
