### ISSUE TITLE
ec2_win_password returns changed state but doesn't change anything

### ISSUE THREAD

**Issue by fd-davidtulloh** [ansible-collections/community.aws#145]
##### SUMMARY

On success, ec2_win_password returns a changed state.

However it doesn't change anything.

```
changed: [pdc.services.hq.adct -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "instance_id": "i-0216d76aa054cd14d",
            "key_data": null,
            "key_file": "- cut -",
            "key_passphrase": null,
            "profile": null,
            "region": "ap-southeast-2",
            "security_token": null,
            "validate_certs": true,
            "wait": false,
            "wait_timeout": 120
        }
    },
    "win_password": "-cut-"
}
```

Happy to prepare a pull request to change this, code change is minor.

However this is backwards incompatible, changes existing behaviour.

**Comment by fd-davidtulloh** [comment]
workaround to produce what I believe is proper behaviour

```
  tasks:
    - ec2_win_password:
        instance_id: "{{ hostvars[inventory_hostname]['instance_id'] }}"
        key_file: "-cut-"
        region: ap-southeast-2
      delegate_to: localhost
      register: password
      changed_when: false
      failed_when: password.win_password == ""
    - set_fact: ansible_password="{{ password.win_password }}" #"
  vars:
    ansible_become: false
```

This is related to #142
