### ISSUE TITLE
aws_ses_identity: can't unset *_notifications topic

### ISSUE THREAD

**Issue by drzraf** [ansible-collections/community.aws#150]
##### SUMMARY
Once a SNS topic is set for a domain's notification, there no known way to remove it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_ses_identity

##### ANSIBLE VERSION
```
ansible 2.9.9
```

##### CONFIGURATION
```
python version = 3.8.2
```

##### OS / ENVIRONMENT
```
boto3_version "1.14.23"
botocore_version "1.17.23
```

##### STEPS TO REPRODUCE
I tried any null, empty-string, empty object variations of the below dict:
```yaml
  aws_ses_identity:
    identity: foo.com
    state: present
    complaint_notifications:
      topic: null
    bounce_notifications:
      topic: null
    feedback_forwarding: True
```

##### EXPECTED RESULTS
The existing topic is unset (See `None` in Amazon UI)

##### ACTUAL RESULTS
- `Failed to set identity notification topic for foo.com Bounce: Parameter validation failed:\nInvalid type for parameter SnsTopic, value: None, type: <class 'NoneType'>, valid types: <class 'str'>"`
- `Failed to set identity notification topic for foo.com Bounce: An error occurred (InvalidParameterValue) when calling the SetIdentityNotificationTopic operation: SNS topic  is invalid.`
