### ISSUE TITLE
Support MinIO when creating users via iam_user

### ISSUE THREAD

**Issue by jsabater** [ansible-collections/community.aws#1587]
### Summary

I am trying to create a user on my single-server, fairly-standard MinIO (latest version) server via `community.aws.iam_user` but the module seems to be asking for a secure token, which I don't have (see playbook below for the error).

Support for buckets on MinIO is already available via `amazon.aws.s3_bucket` and `amazon.aws.s3_bucket module`, but modules `community.aws.iam_user` and `community.aws.iam_access_key` seem to only work with AWS.

This feature request aims at support for MinIO (and other S3-compatible storage servers) to be added to the modules, so that users and service accounts can be created.

### Issue Type

Feature Idea

### Component Name

iam_user

### Additional Information

This is the task I have created to add a new user to the MinIO server:

```yaml
  - name: community.aws | iam_user | create the myprojectuser user account
    community.aws.iam_user:
      ec2_url: https://myminioserver.domain.com:9000
      access_key: "minio-root-user"
      secret_key: "<minio-root-user-password>"
      name: "myprojectuser"
      password: "<myprojectuserpassword"
      state: present
    delegate_to: localhost
```

This is the error returned:

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Endpoint: https://myminioserver.domain.com:9000
fatal: [lxc1.domain.com -> localhost]: FAILED! => {"boto3_version": "1.26.3", "botocore_version": "1.29.3", "changed": false, "msg": "Unable to get user myprojectuser: No endpoint found for parameters:\nUseDualStack: False\nUseFIPS: False\nEndpoint: https://myminioserver.domain.com:9000"
```

So I created the user via the MinIO web console and then tried to create a service account using the `community.aws.iam_access_key`:

```yaml
  - name: community.aws | iam_access_key | create service account on MinIO server
    community.aws.iam_access_key:
      ec2_url: https://myminioserver.domain.com:9000
      access_key: "myprojectuser"
      secret_key: "<myprojectuser-password>"
      user_name: myprojectuser
      state: present
    delegate_to: localhost
    register: srvaccount
```

This is the error returned:

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Endpoint: https://myminioserver.domain.com:9000
fatal: [lxc1.domain.com -> localhost]: FAILED! => {"boto3_version": "1.26.3", "botocore_version": "1.29.3", "changed": false, "msg": "Failed to get access keys for user \"myprojectuser\": No endpoint found for parameters:\nUseDualStack: False\nUseFIPS: False\nEndpoint: https://myminioserver.domain.com:9000"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
