### ISSUE TITLE
Add support for AWS FSX for OpenZFS

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible-collections/community.aws#1651]
### Summary

We are trying to use ansible to automate deployment and maintenance of OpenZFS, if needed we can help testing

### Issue Type

Feature Idea

### Component Name

fsx

### Additional Information

```yaml (paste below)
  - name: Delete an ZFS file system
      fsx_zfs:
        state: absent
        name: "{{ zfs_fs_id }}"
        az: "{{ aws_availability_zone }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
