### ISSUE TITLE
unexpected keyword argument 'date' to deprecate.

### ISSUE THREAD

**Issue by jdnrg** [ansible-collections/community.aws#166]
If you do not pass the purge_policies parameter to iam role, the deprecation warning crashes the code.

https://github.com/ansible-collections/community.aws/blob/39084994955d7894b27c4e9ec370dc7e19cac345/plugins/modules/iam_role.py#L634

````
"module_stderr": 
"Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1595963150.5289385-190-125259151255280/AnsiballZ_iam_role.py\", line 102, in <module>    _ansiballz_main()
  File \"/root/.ansible/tmp/ansible-tmp-1595963150.5289385-190-125259151255280/AnsiballZ_iam_role.py\", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1595963150.5289385-190-125259151255280/AnsiballZ_iam_role.py", line 40, in invoke_module    runpy.run_module(mod_name='ansible_collections.community.aws.plugins.modules.iam_role', init_globals=None, run_name='__main__', alter_sys=True)\n  F\
ile \"/usr/lib64/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.7/runpy.py\"\
, line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\\
n  File \"/tmp/ansible_iam_role_payload_wj2pmw2s/ansible_iam_role_payload.zip/ansible_collections/community/aws/plugins/modules/iam_role.py\", line 666, in <module>\n  
File 
"/tmp/ansible_iam_role_payload_wj2pmw2s/ansible_iam_role_payload.zip/ansible_collections/community/aws/plugins/modules/iam_role.py", line 633, in main\n  File "/tmp/ansible_iam_role_payload_wj2pmw2s/ansible_iam_role_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/core.py", line 179, in deprecate
TypeError: deprecate() got a unexpected keyword argument 'date'
````

**Comment by Akasurde** [comment]
@jdnrg What is Ansible version?

**Comment by jdnrg** [comment]
ansible-playbook 2.9.9
python version = 3.7.6 (default, Feb 26 2020, 20:54:15) [GCC 7.3.1 20180712 (Red Hat 7.3.1-6)]

**Comment by ansibullbot** [comment]
@jdnrg: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ichekaldin** [comment]
I just ran into this issue.

This module execution fails with the listed error:

```
  community.aws.iam_role:
    name: MyRole
    assume_role_policy_document:
      Version: "2008-10-17"
      Statement:
        - Action: "sts:AssumeRole"
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
    description: My test role
    managed_policies:
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    state: present
```

On the other hand, this module execution works fine:

```
  community.aws.iam_role:
    name: MyRole
    assume_role_policy_document:
      Version: "2008-10-17"
      Statement:
        - Action: "sts:AssumeRole"
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
    description: My test role
    purge_policies: true
    managed_policies:
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    state: present
```

Happens with community.aws collection version 1.1.0 and Ansible 2.9.9:

```
$ ansible --version
ansible 2.9.9
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

**Comment by ichekaldin** [comment]
FWIW, similar error happens with `iam_policy` module and `skip_duplicates` attribute:

This fails:

```
  community.aws.iam_policy:
    iam_type: group
    iam_name: MyGroup
    policy_name: MyPolicy
    policy_json: "{{ my_policy_json }}"
    state: present
```

while this works:

```
  community.aws.iam_policy:
    iam_type: group
    iam_name: MyGroup
    policy_name: MyPolicy
    policy_json: "{{ my_policy_json }}"
    skip_duplicates: true
    state: present
```
