### ISSUE TITLE
Add support for creating origin groups in cloudfront_distribution

### ISSUE THREAD

**Issue by kadaan** [ansible-collections/community.aws#169]
##### SUMMARY
Add support for creating origin groups in cloudfront_distribution and using origin groups as targets for behaviors.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cloudfront_distribution

##### ADDITIONAL INFORMATION
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudfront.html#CloudFront.Client.create_distribution_with_tags

```yaml
...
    origin_groups:
        - id: "{{ group_id }}"
          failover_criteria:
            status_codes:
              - 500
              - 502
              - 503
              - 504
          members:
            - origin_id: "{{ primary_id }}"
            - origin_id: "{{ secondary_id }}"
...
```
