### ISSUE TITLE
Add support for AWS managed Active Directory

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible-collections/community.aws#1717]
### Summary

We need to manage the deployment of Active Directory using Ansible
```
  - name: Create an AWS Managed AD
      aws_ad:
        state: absent
        name: "{{ aws_ad_id }}"
        az: "{{ aws_availability_zone }}"
```
We can offer testing in some capacity

### Issue Type

Feature Idea

### Component Name

aws ad

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
