### ISSUE TITLE
Add support for publishing SNS messages on fifo topics

### ISSUE THREAD

**Issue by Pascal-Architrave** [ansible-collections/community.aws#1718]
### Summary

I am trying to publish a message to a fifo SNS topic, but it fails because it is missing the required MessageGroupId parameter. Unfortunately the parameter is not available in the sns module. 
Adding the possibility to add this parameter would be helpful for everyone, because it would be possible to publish messages to FIFO SNS topics, too.

### Issue Type

Feature Idea

### Component Name

sns

### Additional Information

```yaml (paste below)
    - name: "Send request to sns document event topic"
      community.aws.sns:
          msg: "Some message"
          topic: "some_sns_topic"
          subject: "Some subject"
          message_group_id: "foo-bar-1"
```
Link to boto3 documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html?highlight=sns#SNS.Client.publish

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
