### ISSUE TITLE
lightsail - Add firewall settings to lightsail module

### ISSUE THREAD

**Issue by bentaylr** [ansible-collections/community.aws#174]
##### SUMMARY

Extend AWS lightsail module to include additional parameters to configure instance network settings. Including firewall and Static IP binding.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

[community.aws.lightsail]( https://github.com/ansible-collections/community.aws/blob/main/docs/community.aws.lightsail_module.rst)

##### ADDITIONAL INFORMATION

The additional parameters would allow the lightsail instance's firewall desired state to be set. Currently this requires post modification by either aws cli or gui. In addition binding to an existing lightsail static IP would be helpful. 

Suggested yaml format

```yaml

- name: Create a new Lightsail instance, register the instance details
    lightsail:
      state: present
      name: new_instance
      region: ap-southeast-2
      firewall:
        #  application, protocol, port, from
        - ['SSH', 'TCP', 22, '10.10.10.10/24']
        - ['HTTPS', 'TCP', 443, '10.10.10.10/24']
      staticip: static_ip1

```
