### ISSUE TITLE
Ansible support for AWS flow logs

### ISSUE THREAD

**Issue by kwoodson** [ansible-collections/community.aws#1747]
### Summary

I am attempting to create AWS flow logs for my current project that I'm implementing in Ansible and I do not see a way to automate flow logs with the current modules.

`aws ec2 create-flow-logs`

Terraform equivalent: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log

### Issue Type

Feature Idea

### Component Name

ec2_flow_logs

### Additional Information

```yaml (paste below)
 name: create vpc flow logs
  ansible.builtin.command: |
    aws ec2 create-flow-logs --resource-type VPC --resource-ids {{ vpc_id }} --traffic-type ALL --log-group-name {{ flow_group_name }} --deliver-logs-permission-arn {{ flow_log_iam_role_arn }}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
