### ISSUE TITLE
iam_instance_profile: missing functionality

### ISSUE THREAD

**Issue by sean-freeman** [ansible-collections/community.aws#1842]
### Summary

Use of AWS IAM Instance Profiles for managing policies for specified AWS EC2 Instances is missing functionality.

This is not a feature request, it is missing functionality not handled by Ansible Modules `iam_policy` and `iam_user` that is necessary for proper management of AWS IAM for AWS EC2 resources.

**API Reference documents:**
- https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateInstanceProfile.html
- https://docs.aws.amazon.com/IAM/latest/APIReference/API_AddRoleToInstanceProfile.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateIamInstanceProfile.html

**Workaround sample code block using AWS CLI:**

```yaml
- name: Ansible Task block
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    AWS_REGION: "{{aws_region}}"
  block:

    - name: AWS IAM Instance Profile - Create
      ansible.builtin.command: aws iam create-instance-profile
        --instance-profile-name "IAM-Instance-Profile-Test"
      ignore_errors: true

    - name: AWS IAM Instance Profile - Attach AWS IAM Role
      ansible.builtin.command: aws iam add-role-to-instance-profile
        --role-name "IAM-Role-Test"
        --instance-profile-name "IAM-Instance-Profile-Test"
      ignore_errors: true

    - name: AWS EC2 Instances - Attach AWS IAM Instance Profile
      ansible.builtin.command: aws ec2 associate-iam-instance-profile
        --iam-instance-profile "Name=IAM-Instance-Profile-Test"
        --instance-id {{hostvars['hostname'].ansible_board_asset_tag}}
      ignore_errors: true
```

### Issue Type

Bug Report

### Component Name

`iam_instance_profile`

### Ansible Version

```console (paste below)
2.15.0
```

### Collection Versions

```console (paste below)
5.4.0
```

### AWS SDK versions

```console (paste below)
Name: boto3
Version: 1.26.143
---
Name: botocore
Version: 1.29.143
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sean-freeman** [comment]
@tremble GH Issue should not be closed, as the PR does contain any Ansible Module changes to use the AWS IAM Instance Profile and attach to an AWS EC2 instance as a replacement for the following AWS CLI commands:

```yaml
    - name: AWS EC2 Instances - Attach AWS IAM Instance Profile
      ansible.builtin.command: aws ec2 associate-iam-instance-profile
        --iam-instance-profile "Name=IAM-Instance-Profile-Test"
        --instance-id {{hostvars['hostname'].ansible_board_asset_tag}}
      ignore_errors: true
```
