### ISSUE TITLE
Support of EFS Elastic Throughput

### ISSUE THREAD

**Issue by sebaszw** [ansible-collections/community.aws#1884]
### Summary

Add support for the new `elastic` throughput mode of EFS.

The new mode is recommended, so I think it should become the default for the module.

https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-elastic-file-system-elastic-throughput/
https://aws.amazon.com/blogs/aws/new-announcing-amazon-efs-elastic-throughput/

### Issue Type

Feature Idea

### Component Name

efs

### Additional Information

```yaml (paste below)
- name: EFS provisioning
  community.aws.efs:
    state: present
    name: myTestEFS
    throughput_mode: elastic
    tags:
        Name: myTestNameTag
        purpose: file-storage
    targets:
        - subnet_id: subnet-748c5d03
          security_groups: [ "sg-1a2b3c4d" ]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
