### ISSUE TITLE
Ecs task definition error setting environment vars from ssm

### ISSUE THREAD

**Issue by EnolMy** [ansible-collections/community.aws#1894]
### Summary

I'm triing to set env variables to task definition that I get from ssm. I do it by two ways:
 First: Using the dictionary I get from ssm:

```
- name: Get enviroment vars
  set_fact:
    env_content: "{{ lookup('aws_ssm', '/myvariables/development/service1/', profile='test', region='eu-west-1', shortnames=true, bypath=true, recursive=true) }}"

- name: Create task definition
  register: task_output
  community.aws.ecs_taskdefinition:
    family: "{{ stack_name }}"
    state: present
    region: "{{ region }}"
    profile: "{{ aws_profile }}"
    execution_role_arn: "{{ execution_role_arn }}"
    task_role_arn: "{{ task_role_arn }}"
    launch_type: "FARGATE"
    cpu: 2048
    memory: 4096
    network_mode: awsvpc 
    containers:
    - name: "{{ stack_name }}"
      image: "repository/{{ stack_name }}:latest"                                             
      cpu: 1024
      memory: 1024
      essential: true
      environment: "{{ env_content }}"
...
```
But I get this error: 
TypeError: string indices must be integers

Second:
Because the first option didn't wotk, I tried uploading the env file to a S3 bucket and use environmentFiles:
```
- name: Create task definition
  register: task_output
  community.aws.ecs_taskdefinition:
    family: "{{ stack_name }}"
    state: present
    region: "{{ region }}"
    profile: "{{ aws_profile }}"
    execution_role_arn: "{{ execution_role_arn }}"
    task_role_arn: "{{ task_role_arn }}"
    launch_type: "FARGATE"
    cpu: 2048
    memory: 4096
    network_mode: awsvpc 
    containers:
    - name: "{{ stack_name }}"
      image: "REGISTRY/{{ stack_name }}:latest"                                             
      cpu: 1024
      memory: 1024
      essential: true
      environmentFiles: 
        type: "s3" 
        value: "s3://BUCKET_ARN/env_file/.env"
```
But I get the same error:

TypeError: string indices must be integers

### Issue Type

Bug Report

### Component Name

community.aws.ecs_taskdefinition module 

### Ansible Version

```
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/enol.maria/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/enol.maria/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/enol.maria/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/enol.maria/.local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

### Collection Versions

```Collection                    Version
----------------------------- -------
amazon.aws                    6.2.0  
ansible.netcommon             5.1.2  
ansible.posix                 1.5.4  
ansible.utils                 2.10.3 
ansible.windows               1.14.0 
arista.eos                    6.0.1  
awx.awx                       22.5.0 
azure.azcollection            1.16.0 
check_point.mgmt              5.1.1  
chocolatey.chocolatey         1.5.1  
cisco.aci                     2.6.0  
cisco.asa                     4.0.1  
cisco.dnac                    6.7.3  
cisco.intersight              1.0.27 
cisco.ios                     4.6.1  
cisco.iosxr                   5.0.3  
cisco.ise                     2.5.12 
cisco.meraki                  2.15.3 
cisco.mso                     2.4.0  
cisco.nso                     1.0.3  
cisco.nxos                    4.4.0  
cisco.ucs                     1.9.0  
cloud.common                  2.1.3  
cloudscale_ch.cloud           2.3.1  
community.aws                 6.1.0  
community.azure               2.0.0  
community.ciscosmb            1.0.6  
community.crypto              2.14.1 
community.digitalocean        1.23.0 
community.dns                 2.5.7  
community.docker              3.4.8  
community.fortios             1.0.0  
community.general             7.2.0  
community.google              1.0.0  
community.grafana             1.5.4  
community.hashi_vault         5.0.0  
community.hrobot              1.8.1  
community.libvirt             1.2.0  
community.mongodb             1.6.1  
community.mysql               3.7.2  
community.network             5.0.0  
community.okd                 2.3.0  
community.postgresql          2.4.2  
community.proxysql            1.5.1  
community.rabbitmq            1.2.3  
community.routeros            2.8.3  
community.sap                 1.0.0  
community.sap_libs            1.4.1  
community.skydive             1.0.0  
community.sops                1.6.4  
community.vmware              3.8.0  
community.windows             1.13.0 
community.zabbix              2.1.0  
containers.podman             1.10.2 
cyberark.conjur               1.2.0  
cyberark.pas                  1.0.19 
dellemc.enterprise_sonic      2.2.0  
dellemc.openmanage            7.6.1  
dellemc.powerflex             1.7.0  
dellemc.unity                 1.7.0  
f5networks.f5_modules         1.25.0 
fortinet.fortimanager         2.2.0  
fortinet.fortios              2.3.0  
frr.frr                       2.0.2  
gluster.gluster               1.0.2  
google.cloud                  1.2.0  
grafana.grafana               2.1.4  
hetzner.hcloud                1.16.0 
hpe.nimble                    1.1.4  
ibm.qradar                    2.1.0  
ibm.spectrum_virtualize       1.12.0 
infinidat.infinibox           1.3.12 
infoblox.nios_modules         1.5.0  
inspur.ispim                  1.3.0  
inspur.sm                     2.3.0  
junipernetworks.junos         5.2.0  
kubernetes.core               2.4.0  
lowlydba.sqlserver            2.0.0  
microsoft.ad                  1.2.0  
netapp.aws                    21.7.0 
netapp.azure                  21.10.0
netapp.cloudmanager           21.22.0
netapp.elementsw              21.7.0 
netapp.ontap                  22.7.0 
netapp.storagegrid            21.11.1
netapp.um_info                21.8.0 
netapp_eseries.santricity     1.4.0  
netbox.netbox                 3.13.0 
ngine_io.cloudstack           2.3.0  
ngine_io.exoscale             1.0.0  
ngine_io.vultr                1.1.3  
openstack.cloud               2.1.0  
openvswitch.openvswitch       2.1.1  
ovirt.ovirt                   3.1.2  
purestorage.flasharray        1.20.0 
purestorage.flashblade        1.12.1 
purestorage.fusion            1.5.0  
sensu.sensu_go                1.13.2 
servicenow.servicenow         1.0.6  
splunk.es                     2.1.0  
t_systems_mms.icinga_director 1.33.1 
theforeman.foreman            3.12.0 
vmware.vmware_rest            2.3.1  
vultr.cloud                   1.8.0  
vyos.vyos                     4.1.0  
wti.remote                    1.0.5  

# /usr/lib/python3/dist-packages/ansible_collections
Collection                    Version
----------------------------- -------
amazon.aws                    1.4.0  
ansible.netcommon             1.5.0  
ansible.posix                 1.1.1  
ansible.windows               1.4.0  
arista.eos                    1.3.0  
awx.awx                       14.1.0 
azure.azcollection            1.4.0  
check_point.mgmt              1.0.6  
chocolatey.chocolatey         1.0.2  
cisco.aci                     1.1.1  
cisco.asa                     1.0.4  
cisco.intersight              1.0.10 
cisco.ios                     1.3.0  
cisco.iosxr                   1.2.1  
cisco.meraki                  2.2.0  
cisco.mso                     1.1.0  
cisco.nso                     1.0.3  
cisco.nxos                    1.4.0  
cisco.ucs                     1.6.0  
cloudscale_ch.cloud           1.3.1  
community.aws                 1.3.0  
community.azure               1.0.0  
community.crypto              1.4.0  
community.digitalocean        1.0.0  
community.docker              1.2.2  
community.fortios             1.0.0  
community.general             1.3.6  
community.google              1.0.0  
community.grafana             1.1.0  
community.hashi_vault         1.1.0  
community.hrobot              1.1.0  
community.kubernetes          1.1.1  
community.kubevirt            1.0.0  
community.libvirt             1.0.0  
community.mongodb             1.2.0  
community.mysql               1.2.0  
community.network             1.3.2  
community.okd                 1.0.0  
community.postgresql          1.1.1  
community.proxysql            1.0.0  
community.rabbitmq            1.0.1  
community.routeros            1.1.0  
community.skydive             1.0.0  
community.vmware              1.7.0  
community.windows             1.3.0  
community.zabbix              1.2.0  
containers.podman             1.4.1  
cyberark.conjur               1.1.0  
cyberark.pas                  1.0.5  
dellemc.os10                  1.0.2  
dellemc.os6                   1.0.6  
dellemc.os9                   1.0.3  
f5networks.f5_modules         1.7.1  
fortinet.fortimanager         1.0.5  
fortinet.fortios              1.1.8  
frr.frr                       1.0.3  
gluster.gluster               1.0.1  
google.cloud                  1.0.2  
hetzner.hcloud                1.2.1  
ibm.qradar                    1.0.3  
infinidat.infinibox           1.2.4  
junipernetworks.junos         1.3.0  
mellanox.onyx                 1.0.0  
netapp.aws                    20.9.0 
netapp.elementsw              20.11.0
netapp.ontap                  20.12.0
netapp_eseries.santricity     1.1.0  
netbox.netbox                 1.2.1  
ngine_io.cloudstack           1.2.0  
ngine_io.exoscale             1.0.0  
ngine_io.vultr                1.1.0  
openstack.cloud               1.2.1  
openvswitch.openvswitch       1.1.0  
ovirt.ovirt                   1.3.0  
purestorage.flasharray        1.6.2  
purestorage.flashblade        1.4.0  
servicenow.servicenow         1.0.4  
splunk.es                     1.0.2  
theforeman.foreman            1.5.1  
vyos.vyos                     1.1.1  
wti.remote                    1.0.1  

```

### AWS SDK versions

```Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /home/enol.maria/.local/lib/python3.10/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.26.158
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /home/enol.maria/.local/lib/python3.10/site-packages
Requires: botocore, jmespath, s3transfer
Required-by: 
---
Name: botocore
Version: 1.29.161
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /home/enol.maria/.local/lib/python3.10/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer

```

### Configuration

```CONFIG_FILE() = None
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/user/.vault_pass.txt


```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

Just run the task I paste above

### Expected Results

I expect to retrieve the params from ssm and set it to ecs task definition

### Actual Results

```TASK [aws-ecs-deployment : Create task definition] ***************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: string indices must be integers
fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/enol.maria/.ansible/tmp/ansible-tmp-1690193609.9547431-30177-2027996249570/AnsiballZ_ecs_taskdefinition.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/enol.maria/.ansible/tmp/ansible-tmp-1690193609.9547431-30177-2027996249570/AnsiballZ_ecs_taskdefinition.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/enol.maria/.ansible/tmp/ansible-tmp-1690193609.9547431-30177-2027996249570/AnsiballZ_ecs_taskdefinition.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.aws.plugins.modules.ecs_taskdefinition', init_globals=dict(_module_fqn='ansible_collections.community.aws.plugins.modules.ecs_taskdefinition', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.aws.ecs_taskdefinition_payload_ldpl1r57/ansible_community.aws.ecs_taskdefinition_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_taskdefinition.py\", line 1196, in <module>\n  File \"/tmp/ansible_community.aws.ecs_taskdefinition_payload_ldpl1r57/ansible_community.aws.ecs_taskdefinition_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_taskdefinition.py\", line 975, in main\nTypeError: string indices must be integers\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
