### ISSUE TITLE
sns_topic - subscriptions section lacks setting the raw message delivery option

### ISSUE THREAD

**Issue by madcowthafirst** [ansible-collections/community.aws#193]
##### SUMMARY

The sns_topic module doesn't allow setting the raw message delivery option for subscriptions.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

sns_topic

##### ADDITIONAL INFORMATION

Get a new option within the subscriptions section with the name of raw_message with
a default value of disabled. 

We need the raw message delivery option to be enabled on all of our subscriptions. Not having the ability to set this with Ansible requires us to manually set this option to true for all our subscriptions across all our topics.

```yaml
      subscriptions:
       - endpoint: "{{ item.1.queue_arn }}"
         protocol: "sqs"
         raw_message: "enabled"
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/sns_topic.py`](https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/sns_topic.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jillr @joelthompson @nand0p @s-hertel @tremble @willthames @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by canidam** [comment]
Any updates on this issue?

**Comment by ansibullbot** [comment]
cc @markuman
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by markuman** [comment]
Hi @canidam  
thx for comming back to this issue.  
Unfortunately no one is currently working on this feature request at the moment.

Just some notes about the implementation that is necessary for this feature.

The requested option is an attribute of the subscription: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html#SNS.Client.subscribe  
and a subscription can have multiple attributes. Therefore, the implementation should will looks more like this I guess

```yml
      subscriptions:
       - endpoint: "{{ item.1.queue_arn }}"
         protocol: "sqs"
         attributes:
           raw_message_delivery: yes
```
