### ISSUE TITLE
Supports EBS throughput for ec2_launch_template.py

### ISSUE THREAD

**Issue by free88dom** [ansible-collections/community.aws#1944]
### Summary

I'd like to have an option to specify custom throughput when creating a LaunchTemplate. Only IOPS can be specified in block_device_mapping as of now.
        
As of now, boto3 has this feature already implemented https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/create_launch_template.html

       

### Issue Type

Feature Idea

### Component Name

ec2_launch_template.py

### Additional Information

```yaml (paste below)
block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        volume_size: "{{ item.disk_volume_size | default(20) }}"
        volume_type: gp3
        delete_on_termination: true
        throughput: 500
        iops: 5000
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
