### ISSUE TITLE
add an MSK broker instance type

### ISSUE THREAD

**Issue by shblue21** [ansible-collections/community.aws#1946]
### Summary

Broker instances of MSK with the current provisioning type can be selected up to m5.24xlarge, but only m5.4xlarge is available for the ansible module.

### Issue Type

Feature Idea

### Component Name

msk_cluster

### Additional Information

```yaml (paste below)
- name: create msk cluster
  msk_cluster:
    name: test-msk-cluster
    state: present
    version: "2.8.1"
    nodes: 2
    ebs_volume_size: 10
    subnets: subnet-temp
    wait: true
    instance_type: "kafka.m5.8xlarge"
```

recevied error message that
`FAILED! => {"changed": false, "msg": "value of instance_type must be one of: kafka.t3.small, kafka.m5.large, kafka.m5.xlarge, kafka.m5.2xlarge, kafka.m5.4xlarge, got: kafka.m5.8xlarge"}`

- https://docs.aws.amazon.com/msk/latest/developerguide/msk-create-cluster.html#broker-instance-types

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
