### ISSUE TITLE
aws.elb_target_group.targets.Port try to convert string to integer to allow use of jinja2 vars

### ISSUE THREAD

**Issue by mdhirt** [ansible-collections/community.aws#1996]
### Summary

I am trying to instantiate an aws elb target group using ansible variables to specifiy the target instance id and port.

When using ansible variables and jinja2 syntax and integer value for port is always returned as a string.

Can this module please try to convert the value provided for Port from a string value to an integer so it doesn't throw an Invalid Type error.

When running the provided sample ansible task the following error is thrown due to jinja2 always returning strings - see https://github.com/ansible/ansible/issues/30366 

TASK [apigateway : Create ELB Target Group] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Targets[0].Port, value: 9443, type: <class 'str'>, valid types: <class 'int'>
fatal: [awscli]: FAILED! => changed=false 
  boto3_version: 1.28.25
  botocore_version: 1.31.25
  msg: |-
    Couldn't register targets: Parameter validation failed:
    Invalid type for parameter Targets[0].Port, value: 9443, type: <class 'str'>, valid types: <class 'int'>

(venv):~/$ ansible-galaxy collection list

.ansible/collections/ansible_collections
Collection                    Version
----------------------------- -------
amazon.aws                    6.4.0  
community.aws                 6.3.0  
community.crypto              2.15.1 
community.general             7.4.0  

$ ansible --version
ansible [core 2.15.6]
  config file = /ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /venv/lib/python3.10/site-packages/ansible
  ansible collection location = /.ansible/collections:/usr/share/ansible/collections
  executable location = /venv/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True

### Issue Type

Feature Idea

### Component Name

elb_target_group

### Additional Information

```yaml (paste below)
- name: Set vars for target group
  ansible.builtin.set_fact:
    tg_name: "tg-test"
    tg_protocol: HTTPS
    tg_protvers: HTTP1
    tg_port: 9443
    tg_vpc_id: "{{ vpc_id }}"
    tg_healthcheck_proto: HTTPS
    tg_healthcheck_path: /health
    tg_healthcheck_response: 200
    tg_healthcheck_interval: 5
    tg_healthcheck_timeout: 3
    tg_healthy_threshold_count: 4
    tg_unhealthy_threshold_count: 3
    tg_ipaddrtype: ipv4
    tg_region: "{{ aws_region }}"
    tg_targettype: instance
    tg_target_instance_id: "i-12345678"

- name: Create ELB Target Group
  community.aws.elb_target_group:
    state: present
    name: "{{ tg_name }}"
    protocol: "{{ tg_protocol }}"
    port: "{{ tg_port }}"
    vpc_id: "{{ tg_vpc_id }}"
    health_check_protocol: "{{ tg_healthcheck_proto }}"
    health_check_path: "{{ tg_healthcheck_path }}"
    successful_response_codes: "{{ tg_healthcheck_response }}"
    health_check_interval: "{{ tg_healthcheck_interval }}"
    health_check_timeout: "{{ tg_healthcheck_timeout }}"
    healthy_threshold_count: "{{ tg_healthy_threshold_count }}"
    unhealthy_threshold_count: "{{ tg_unhealthy_threshold_count }}"
    targets: 
      - Id: "{{ tg_target_instance_id }}"
        Port: "{{ tg_port }}"
    wait_timeout: 300
    wait: True
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
Try casting it as an int in your playbook

```yml
Port: "{{ tg_port | int }}"
```

**Comment by markuman** [comment]
Converting some string straight into an integer can cause a whole host of other problems.... I don't feel like it should be implemented, because the documentation is clear. [Port input must be an integer](https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/elb_target_group.py#L77-L82).

**Comment by mdhirt** [comment]
> Try casting it as an int in your playbook
> 
> ```yaml
> Port: "{{ tg_port | int }}"
> ```

Casting as Int results in the same error message.  This is a problem with jinja2.  If I set the value by hardcoding 9443 it works but as soon as I use a jinja2 variable it errors.

**Comment by markuman** [comment]
I cannot reproduce using community.aws 6.3.0 and ansible 2.15.5


```yml
---
- hosts: localhost
  tasks:

    - name: find instance id of box
      ec2_instance_info:
        region: eu-central-1
        filters:
          "tag:Name": some-instance-name
      register: box

    - name: test target group
      elb_target_group:
        name: deleteme-01
        protocol: https
        port: 443
        vpc_id: vpc-123456
        health_check_path: /login
        health_check_port: 443
        health_check_protocol: https
        healthy_threshold_count: 2
        deregistration_delay_timeout: 60
        successful_response_codes: "200,302,400"
        health_check_timeout: 5
        state: present
        modify_targets: yes
        targets:
          - Id: "{{ box.instances[0].instance_id }}"
            Port: "{{ '443' | int }}"

```

results in

```
PLAY [localhost] ***************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [find instance id of box] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [test target group] *******************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
