### ISSUE TITLE
Indentation inconsistent on cloudfront_distribution module

### ISSUE THREAD

**Issue by RHeynsZa** [ansible-collections/community.aws#2008]
### Summary

A few things seem to be inconsistently indented on the  cloudfront_distribution module

ie Look at `viewer_protocol_policy` seems to be indented under `forwarded_values`, however, under the example, it isnt under `forwarded_values` at all

```
    default_cache_behavior:
      target_origin_id: 'my test origin-000111'
      forwarded_values:
        query_string: true
        cookies:
          forward: all
        headers:
         - '*'
      viewer_protocol_policy: allow-all
      smooth_streaming: true
      compress: true
```

Its hard to know which properties go where, by following this

### Issue Type

Documentation Report

### Component Name

cloudfront_distribution

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.0]
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
amazon.aws                    7.0.0
community.aws                 7.0.0
netapp.aws                    21.7.1
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
