### ISSUE TITLE
Add support for "skip_matching" preference in autoscaling_instance_refresh

### ISSUE THREAD

**Issue by gtie** [ansible-collections/community.aws#2016]
### Summary

AWS enables users to turn on a "skip_matching" preference when starting an Instance Refresh. The Ansible module OTOH does not expose that preference.

### Issue Type

Feature Idea

### Component Name

autoscaling_instance_refresh

### Additional Information

Once implemented the following should work:
```yaml (paste below)
    - name: START INSTANCE REFRESH
      community.aws.ec2_asg_instance_refresh:
        name: "{{ asg_name }}"
        state: started
        preferences:
          skip_matching: true
```

Looking at the code of the current Ansible module, the only real change is to add it to the list of allowed preferences and document it. The plumbing is already there to support passing that preference to the AWS API.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
