### ISSUE TITLE
eks_cluster should be able to upgrade cluster versions

### ISSUE THREAD

**Issue by davidfox79** [ansible-collections/community.aws#2053]
### Summary

I created a cluster using the eks_cluster module. Now I want to be able to define a new state in terms of the verion of the cluster (1.24 -> 1.25 for example. Changing the value should result in a cluster upgrade. This would provide us with an idempotent way of maintaining the desired state of the cluster

### Issue Type

Feature Idea

### Component Name

eks_cluster

### Additional Information

```yaml (paste below)
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Create an EKS cluster
      community.aws.eks_cluster:
        name: "{{ cluster_name }}"
        version: 1.25
        role_arn: "{{ rarn }}"
        region: "{{ region }}"
        subnets: "{{ subnets }}"
        security_groups: "{{ sgs }}"
        wait: true

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
