### ISSUE TITLE
networkfirewall_policy should allow managed stateful rule group to run in alert mode

### ISSUE THREAD

**Issue by linusguan** [ansible-collections/community.aws#2100]
### Summary

When add or update managed stateful groups, AWS allows you to run it in alert mode. This is very useful when there is false positive and you want to disable a managed rule group temporarily.
While you can do it in the console, the Ansible module currently does not allow you to specify a mode when adding managed stateful rule group.

<img width="830" alt="image" src="https://github.com/ansible-collections/community.aws/assets/26048569/637769f4-b0bc-4ea4-b789-987442fef8c2">

### Issue Type

Feature Idea

### Component Name

networkfirewall_policy

### Additional Information

```yaml (paste below)
- name: NFW policy
  community.aws.networkfirewall_policy:
    name: 'test-1'
    state: present
    region: "ap-southeast-2"
    stateful_rule_groups:
      - name: "arn:aws:network-firewall:ap-southeast-2:aws-managed:stateful-rulegroup/AbusedLegitMalwareDomainsStrictOrder"
        alert_mode: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
