### ISSUE TITLE
autoscaling_instance_refresh: add "max_healthy_percentage" (MaxHealthyPercentage)

### ISSUE THREAD

**Issue by steadfasterX** [ansible-collections/community.aws#2120]
### Summary

I want to ensure that a new instance gets started first before an older one get killed. according to the [AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/start-instance-refresh.html) this should be possible by setting `MaxHealthyPercentage` higher than 100.

### Issue Type

Feature Idea

### Component Name

autoscaling_instance_refresh

### Additional Information

```yaml (paste below)

- name: "Refresh: {{ aws_autoscaling_grpname }}"
  community.aws.autoscaling_instance_refresh:
    aws_access_key: "{{ vault_aws_access_key }}"
    aws_secret_key: "{{ vault_aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ aws_autoscaling_grpname }}"
    preferences:
      min_healthy_percentage: "{{ aws_autoscaling_min_healthy_perc }}"
      instance_warmup: "{{ aws_autoscaling_warmup }}"
      max_healthy_percentage: 110 # <------------------
    state: started
  register: refreshid
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
