### ISSUE TITLE
Incorrect usage of variables in `redshift_info` `EXAMPLES`

### ISSUE THREAD

**Issue by sivel** [ansible-collections/community.aws#2297]
### Summary

The `EXAMPLES` for `redshift_info` show an example of:

```yaml
- name: Fail if no cluster(s) is/are found
  community.aws.redshift_info:
    tags:
      env: stg
      stack: db
  register: redshift_user
  failed_when: "{{ redshift_user.results | length == 0 }}"
```

The jinja2 delimiters should be removed such as:

```diff
-   failed_when: "{{ redshift_user.results | length == 0 }}"
+   failed_when: redshift_user.results | length == 0
```

### Issue Type

Documentation Report

### Component Name

redshift_info

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

N/A

### Additional Information

N/A

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
