### ISSUE TITLE
Add support for Resource Access Manager (AWS RAM) resource shares

### ISSUE THREAD

**Issue by kilitr** [ansible-collections/community.aws#2316]
### Summary

I am trying to share ssm parameters with other aws accounts.

As this is neither supported by the official aws ansible collection nor this community one, i am creating this feature request.

i want to be able to allow other accounts to read ssm parameters in my account which heavily relies on ansible to create these parameters.

### Issue Type

Feature Idea

### Component Name

ram_resource_share

### Additional Information

```yaml (paste below)
- name: Create or update RAM resource share for SSM parameter
  community.aws.ram_resource_share:
    name: "my-resource-share"
    allow_external_principals: true
    principals:
      - 123456789012
      - 234567890123
    resources:
      - "{{ item.ssm_path }}"
    resource_type: "ssm:parameter"
    region: "{{ aws_region }}"
    state: present
  loop: "{{ ami_configs }}"
  when: shared_accounts|length > 0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
