### ISSUE TITLE
Add string as key/value to AWS Secrets Manager

### ISSUE THREAD

**Issue by gowthamakanthan** [ansible-collections/community.aws#245]
##### SUMMARY

``` community.aws.aws_secret``` is allowing to add the secret as a plaintext, Could you please enable to save as key/value?

##### ISSUE TYPE
Add string as key/value to AWS Secrets Manager.

##### COMPONENT NAME
community.aws.aws_secret

##### ADDITIONAL INFORMATION

```yaml

Following the module document to add the secrets in AWS secret. This play allowing to add as plaintext, would like to have the option for adding as key/value.

- name: Add string to AWS Secrets Manager
  community.aws.aws_secret:
    name: 'test_secret_string'
    state: present
    secret_type: 'string'
    secret: "{{ super_secret_string }}"

```
