### ISSUE TITLE
Add a module to manage AWS Lightsail Static IPs

### ISSUE THREAD

**Issue by danielcotton** [ansible-collections/community.aws#250]
##### SUMMARY
Issue #174 requests adding the ability to manage firewall and static IP settings in a Lightsail VPS. I suggest that it may be beneficial to have a module that can manage static IPs for Lightsail (which are managed seperately from VMs).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.aws.lightsail

##### ADDITIONAL INFORMATION
In Lightsail, static IP addresses are managed separately from VPSes. You create and manage static IPs, and can attach them to a VPS as per #174. A module that can mange these IPs would be a prerequisite for end-to-end configuration management for Lightsail.

I already have a basic version of this and am planning on submitting a PR in the next couple of weeks once it's cleaned up & tested

Relevant API Documentation:

* https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_AllocateStaticIp.html
* https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_GetStaticIps.html
* https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_ReleaseStaticIp.html

Possible Playbook notation:
```yaml
- name: Create a new Lightsail static IP
  community.aws.lightsail_static_ip:
    state: present
    name: static_ip_1
    aws_access_key: XXXXXXXX
```
