### ISSUE TITLE
elements='dict' set suboptions to None values

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.aws#251]
##### SUMMARY

https://github.com/ansible-collections/community.aws/commit/059cf9efc95bb976de21ab4f8e4d9ddd001983fc#diff-b6b6dcee788bed9e4eb606cc7bb24cddR2102

This commit introduces `elements='dict'` which results in `None` values for suboptions like `block_device_mappings` or `network_interfaces`.  
With community.aws 1.0.0 everything is fine. Since 1.2.0 it gets broken.  
The integration test does not cover it, because it set nor `block_device_mappings` nor `network_interfaces`.

@felixfontein and @s-hertel confirms this bug on #ansible-aws

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_launch_template  
_and maybe many more..._

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.10.1
  config file = /home/m/git/lekker/ansible/ansible.cfg
  configured module search path = ['/home/m/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/m/.local/lib/python3.8/site-packages/ansible
  executable location = /home/m/.local/bin/ansible
  python version = 3.8.5 (default, Sep  5 2020, 10:50:12) [GCC 10.2.0]


ansible-galaxy collection list

# /home/m/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
amazon.aws         1.2.0  
ansible.netcommon  1.3.0  
ansible.posix      1.1.0  
community.aws      1.2.0  
google.cloud       1.0.0  
hetzner.hcloud     1.0.0  
markuman.nextcloud 2.0.1  
```

##### STEPS TO REPRODUCE

```yaml
- name: create launch template for autoscaling group cluster-int
  community.aws.ec2_launch_template:
    template_name: cluster-int
    image_id: "{{ ami.images[0].image_id }}"
    instance_type: "{{ launch_template_instance_type }}"
    credit_specification:
      cpu_credits: "{{ CPU_CREDITS | default('standard') }}"
    network_interfaces:
      - associate_public_ip_address: no
        delete_on_termination: yes
        device_index: 0
        groups:
          - "{{ ecsinstanceint.group_id }}"
          - "{{ ECS_SG_1.group_id }}"
          - "{{ ECS_SG_2.group_id }}"
          - "{{ awsservicegroupS3.group_id }}"
          - "{{ elb_net_int_sg.group_id }}"
          - "{{ GLOBAL_SG_1.group_id }}"
          - "{{ GLOBAL_SG_2.group_id }}"
        # subnet_id: subnet-c84506a3
    user_data: "{{ USERDATA | b64encode }}"
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    iam_instance_profile: ecsInstanceRole
    ebs_optimized: yes
    block_device_mappings:
      - device_name: /dev/xvda
        ebs:
          volume_size: 30
          volume_type: gp2
          delete_on_termination: true
          kms_key_id: "{{ kms_key }}"
          encrypted: yes
    tags:
      cluster: cluster-int
      System: ecs
      Name: cluster-int:xvda
      ssh_access: ldap
      ssh_pub_key: ldap
  register: NEW_LAUNCH_TEMPLATE
```

##### ACTUAL RESULTS

```

Invalid type for parameter LaunchTemplateData.NetworkInterfaces[0].Description, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
--
Invalid type for parameter LaunchTemplateData.NetworkInterfaces[0].Ipv6AddressCount, value: None, type: <class 'NoneType'>, valid types: <class 'int'>
Invalid type for parameter LaunchTemplateData.NetworkInterfaces[0].Ipv6Addresses, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter LaunchTemplateData.NetworkInterfaces[0].NetworkInterfaceId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter LaunchTemplateData.NetworkInterfaces[0].PrivateIpAddress, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter LaunchTemplateData.NetworkInterfaces[0].SubnetId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter LaunchTemplateData.BlockDeviceMappings[0].Ebs.Iops, value: None, type: <class 'NoneType'>, valid types: <class 'int'>
Invalid type for parameter LaunchTemplateData.BlockDeviceMappings[0].Ebs.SnapshotId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter LaunchTemplateData.BlockDeviceMappings[0].NoDevice, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter LaunchTemplateData.BlockDeviceMappings[0].VirtualName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

```
