### ISSUE TITLE
Wrong datatype in ecs_taskdefinition.containers 

### ISSUE THREAD

**Issue by iljau** [ansible-collections/community.aws#264]
https://github.com/ansible-collections/community.aws/blob/6eab8b0c0e805fe8881a834f4f1329193396fd0a/plugins/modules/ecs_taskdefinition.py#L324

In current version argument_spec is following:
`containers=dict(required=False, type='list', elements='str'),`

This causes dicts inside container list to be converted to strings.

If we select some example from documentation ...
```
- name: Create task definition
  community.aws.ecs_taskdefinition:
    family: nginx
    containers:
    - name: nginx
      essential: true
      image: "nginx"
      portMappings:
      - containerPort: 8080
        hostPort:      8080
      cpu: 512
      memory: 1024
    state: present
```

... then running it causes following exception:
```
  File "[..]/debug_dir/ansible_collections/community/aws/plugins/modules/ecs_taskdefinition.py", line 353, in main
    for environment in container.get('environment', []):
AttributeError: 'str' object has no attribute 'get'
```

To get examples (and container section) working, argument spec needs to be changed to following:
`containers=dict(required=False, type='list', elements='dict'),`
