### ISSUE TITLE
aws_s3_cors broken. String/dict Parameter validation failed

### ISSUE THREAD

**Issue by nicolastorres** [ansible-collections/community.aws#269]
##### SUMMARY

aws_s3_cors 
python version = 3.6.12
Ansible version = 2.10
boto3_version= 1.15.18
botocore_version= 1.18.18

Using the sample playbook I'm unable to update cors on S3.
Please let me know if I can provide additional details.

```yaml
task:
    - community.aws.aws_s3_cors:
        name: "{{ site_dns }}"
        state: present
        rules:
         - allowed_headers: Authorization
```
Error output:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.aws.aws_s3_cors_payload_o_7zhenk/ansible_community.aws.aws_s3_cors_payload.zip/ansible_collections/community/aws/plugins/modules/aws_s3_cors.py", line 125, in create_or_update_bucket_cors
  File "/ops/ansible3/local/lib/python3.6/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/ops/ansible3/local/lib/python3.6/dist-packages/botocore/client.py", line 649, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/ops/ansible3/local/lib/python3.6/dist-packages/botocore/client.py", line 697, in _convert_to_request_dict
    api_params, operation_model)
  File "/ops/ansible3/local/lib/python3.6/dist-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter CORSConfiguration.CORSRules[0], value: {'allowed_headers': 'Authorization'}, type: <class 'str'>, valid types: <class 'dict'>
[WARNING]: The value "rules: {'allowed_headers': 'Authorization'}" (type dict) was converted to "rules: "{'allowed_headers':
'Authorization'}"" (type string). If this does not look like what you expect, quote the entire value to ensure it does not
change.
fatal: [localhost]: FAILED! => {
    "boto3_version": "1.15.18",
    "botocore_version": "1.18.18",
    "changed": false,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "name": "test-bucket.com",
            "profile": null,
            "region": null,
            "rules": [
                "{'allowed_headers': 'Authorization'}"
            ],
            "security_token": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "Unable to update CORS for bucket test-bucket.com: Parameter validation failed:\nInvalid type for parameter CORSConfiguration.CORSRules[0], value: {'allowed_headers': 'Authorization'}, type: <class 'str'>, valid types: <class 'dict'>"
}
```

##### ANSIBLE VERSION

2.10

##### COMPONENT NAME

aws_s3_cors

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
@nicolastorres: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/aws_s3_cors.py`](https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/aws_s3_cors.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @fivethreeo @jillr @s-hertel @tremble @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by markuman** [comment]
@nicolastorres 

Just follow the example from the documentation: https://docs.ansible.com/ansible/latest/collections/community/aws/aws_s3_cors_module.html#examples  
You just need to put your values in lists.  

```diff
- - allowed_headers: Authorization
+ - allowed_headers:
+     - Authorization
```

Furthermore, only `allowed_headers` is not sufficient. You also need to define `allowed_methods` and  `allowed_origins` . 

```yml
---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: eu-central-1

  tasks:
    - name: test
      community.aws.aws_s3_cors:
        name: "{{ site_dns }}"
        state: present
        rules:
          - allowed_origins:
              - http://www.example.com/
            allowed_methods:
              - GET
              - POST
            allowed_headers:
              - Authorization
            expose_headers:
              - x-amz-server-side-encryption
              - x-amz-request-id
            max_age_seconds: 30000
```
