### ISSUE TITLE
Syntax error in "aws_kms_info" example for filtering by tag

### ISSUE THREAD

**Issue by daurrutia** [ansible-collections/community.aws#276]
##### SUMMARY

*"HINT: Did you know the documentation has an "Edit on GitHub" link on every page ?"*
*I did not see this feature.*

The example for tag filtering below:
```
# Gather information about all keys with a specific name
- community.aws.aws_kms_info:
    filters:
      "tag:Name": Example
```

Ought to read:
```
# Gather information about all keys with a specific name
- community.aws.aws_kms_info:
    filters:
      "tags:Name": Example
```

https://docs.ansible.com/ansible/latest/collections/community/aws/aws_kms_info_module.html

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

community.aws.aws_kms_info

##### ANSIBLE VERSION

```paste below
2.10.2
```

**Comment by markuman** [comment]
What the exactly error message you got?  
I cannot reproduce it.

```
---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: test
      community.aws.aws_kms_info:
        filters:
          "tags:Name": Example
```

works fine. With communit.aws 1.0.0 and also with current version 1.2.1
