### ISSUE TITLE
ecs_task doesn't have assignPublicIp param in network_configuration

### ISSUE THREAD

**Issue by kagarlickij** [ansible-collections/community.aws#319]
##### SUMMARY
`ecs_task` doesn't have `assignPublicIp` param in `network_configuration`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ecs_task

##### ANSIBLE VERSION
```
2.10.3
```

##### CONFIGURATION

all default

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- name: RUN a task on Fargate
  ecs_task:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    operation: run
    cluster: "{{ cluster_name }}"
    task_definition: "{{ task_definition_name }}"
    count: 1
    started_by: ansible_user
    launch_type: FARGATE
    network_configuration:
      subnets:
      - "{{ subnet_id }}"
      security_groups:
      - "{{ security_group_id }}"
      assignPublicIp: "ENABLED"
  register: task_output
```

##### EXPECTED RESULTS
I expect `assignPublicIp: "ENABLED"` to create task with Public IP as per AWS documentation: "assignPublicIp -> (string)
Whether the task's elastic network interface receives a public IP address. The default value is DISABLED ."

Without Public IP task can't pull Docker image and use CloudWatch 

##### ACTUAL RESULTS
https://docs.ansible.com/ansible/latest/collections/community/aws/ecs_task_module.html#parameter-network_configuration doesn't have this option
