### ISSUE TITLE
community.aws.ec2_eip allocates a new address on every call

### ISSUE THREAD

**Issue by fredrik-jansson-se** [ansible-collections/community.aws#323]
##### SUMMARY
I have an ansible script that deploys a customer in a new VPC, for the VPC I need a single EIP. With the current ec2_eip I can't create an idempotent script that only allocates an EIP the first time.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.aws.ec2_eip

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /home/frja/code/customer-automation/ansible.cfg
  configured module search path = ['/home/frja/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/frja/code/customer-automation/venv/lib/python3.8/site-packages/ansible
  executable location = /home/frja/code/customer-automation/venv/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/frja/code/customer-automation/ansible.cfg) = True
HOST_KEY_CHECKING(/home/frja/code/customer-automation/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
- name: Create Elastic IP
  community.aws.ec2_eip:
    in_vpc: true
    allow_reassociation: true
    reuse_existing_ip_allowed: true
    tag_name: nginx-ingress-for
    tag_value: "{{aws.vpc}}"
  register: eip

```

##### EXPECTED RESULTS
I expect the eip to be tagged according to the above and on second run, no new eip is allocated. I also expected the tags to be set on the EIP, but none are set.

##### ACTUAL RESULTS

A new eip is allocated on each run and no tags are set on the EIP.

```paste below

```
