### ISSUE TITLE
EIP items should allow tagging.

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ansible-collections/community.aws#331]
##### SUMMARY
While it's possible to create an EIP (with `community.aws.ec2_eip`) and then tag it (with `community.aws.ec2_tag`), it would be much more useful and concise to make it so that `ec2_eip` would also permit you to tag the object.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.aws.ec2_eip

##### ADDITIONAL INFORMATION
Currently you need to do this:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - community.aws.ec2_eip:
      region: "{{ item.region }}"
      device_id: "{{ item.device_id }}"
      private_ip_address: "{{ item.private_ip_address }}"
      state: present
      in_vpc: true
    register: ec2_allocation
    loop: [{'name': 'demo_eip', 'region': 'eu-west-1', 'device_id': 'eni-01234567890abcdef', 'private_ip': '192.0.2.15'}]
  - amazon.aws.ec2_tag:
      region: "{{ item.invocation.module_args.region }}"
      resource: "{{ item.allocation_id }}"
      state: present
      tags:
        Name: "{{ item.item.name }}"
    loop: "{{ ec2_allocation.results }}"
```

It would be better if you could do this:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - community.aws.ec2_eip:
      region: eu-west-1
      device_id: eni-01234567890abcdef
      private_ip_address: 192.0.2.15
      tags:
        Name: demo_eip
      state: present
      in_vpc: true
```
