### ISSUE TITLE
ec2_vpc_nat_gateway should support tags

### ISSUE THREAD

**Issue by acrawly** [ansible-collections/community.aws#345]
##### SUMMARY
The ec2_vpc_nat_gateway module does not support tags and it should. NAT Gateways support tags in AWS.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
The module name is ec2_vpc_nat_gateway

##### ADDITIONAL INFORMATION
The ec2_vpc_nat_gateway should accept a dictionary of tags, like the internet gateway module (as documented [here](https://docs.ansible.com/ansible/latest/collections/community/aws/ec2_vpc_igw_module.html)).

```yaml
- name: setup NAT gateways
  tags: always
  ec2_vpc_nat_gateway:
    profile: your_aws_profile
    state: present
    region: us-west-1
    subnet_id: "{{ item }}"
    if_exist_do_not_create: yes
    tags: #<-- This is currently not supported
      - Name: MyNATGateway
      - Purpuse: NATing things 
  loop: "{{nat_subnet_list}}" #This is an array of subnet IDs in format `nat_subnet_id: subnet-12345, subnet-54321`

```
