### ISSUE TITLE
feat: add tag support to iam_user

### ISSUE THREAD

**Issue by Tyler-2** [ansible-collections/community.aws#36]
##### SUMMARY

Support assignment of AWS tags to IAM users.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

iam_user

##### ADDITIONAL INFORMATION

Tags are a standard, often crucial organizational part of AWS objects. It is the opinion of the PR author that tagging should be a requirement of new modules, where the underlying AWS object supports it.

```yaml

# Create a user and attach a managed policy using its ARN
- iam_user:
    name: testuser1
    managed_policy:
      - arn:aws:iam::aws:policy/AmazonSNSFullAccess
    tags:
        - department: corpdepartment
        - repo: user_deployment_repo
        - classification: sensitive
    state: present
```
