### ISSUE TITLE
 community.aws.ec2_eip  error Invalid type for parameter Domain,

### ISSUE THREAD

**Issue by kristijorgji** [ansible-collections/community.aws#374]
##### ISSUE TYPE
- Bug Report

##### SUMMARY
Error while trying to create eip

My files and details are below

`roles/infra/defaults/main.yml`
```
---

aws_vpc_eip_default_region: eu-central-1

aws_vpc_eip_release_on_disassociation: False
aws_vpc_eip_reuse_existing_ip_allowed: False

# secret creds here  for aws

aws_vpc_eips: []
```

the task that fails
`roles/infra/tasks/main.yml`
 
```
---

- name: ensure eip is created if none exists
  community.aws.ec2_eip:
    state: present
    # Optional values
    release_on_disassociation: "{{ eip.release_on_disassociation | default(aws_vpc_eip_release_on_disassociation) }}"
    reuse_existing_ip_allowed: "{{ eip.reuse_existing_ip_allowed | default(aws_vpc_eip_reuse_existing_ip_allowed) }}"
    public_ip: "{{ eip.public_ip | default(omit) }}"
    region: "{{ eip.region | default(aws_vpc_eip_default_region | default(omit)) }}"
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit)  }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_eip_profile | default(omit) }}"
  register: _aws_vpc_eip
```

All aws envs are set properly, have other modules work fine. Also error is not related to auth issue

Gives following error message:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Domain, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
fatal: [kubernetes]: FAILED! => {"boto3_version": "1.13.17", "botocore_version": "1.16.17", "changed": false, "msg": "Couldn't allocate Elastic IP address: Parameter validation failed:\nInvalid type for parameter Domain, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>"}
```

##### COMPONENT NAME
community.aws.ec2_eip

##### ANSIBLE VERSION
ansible 2.9.9

##### CONFIGURATION
command shows empty

##### OS / ENVIRONMENT

ubuntu 18.04

##### STEPS TO REPRODUCE
The yaml files are given above

##### EXPECTED RESULTS
The eip should be created

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Domain, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
fatal: [kubernetes]: FAILED! => {"boto3_version": "1.13.17", "botocore_version": "1.16.17", "changed": false, "msg": "Couldn't allocate Elastic IP address: Parameter validation failed:\nInvalid type for parameter Domain, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>"}
```
