### ISSUE TITLE
[s3_sync] Add support for setting Content-Length metadata on uploaded files

### ISSUE THREAD

**Issue by sobotklp** [ansible-collections/community.aws#376]
##### SUMMARY
Add support for setting the `Content-Length` metadata when uploading files to S3 using the `s3_sync` plugin.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
s3_sync

##### ADDITIONAL INFORMATION
Cloudfront supports automatically gzip-compressing certain file types (e.g. .js, .css), but it requires that the `Content-Length` metadata is specified. See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html for more details.

```yaml
- name: basic upload_with_content_length
  community.aws.s3_sync:
    bucket: tedder
    file_root: roles/s3/files/
    content_length: True
```
