### ISSUE TITLE
[ec2_vpc_nat_gateway] CI pipeline fails with RequestLimitExceeded errors

### ISSUE THREAD

**Issue by alinabuzachis** [ansible-collections/community.aws#379]
##### SUMMARY
CI pipeline not successful for the **ec2_vpc_nat_gateway** module due due to `RequestLimitExceeded`errors.

`fatal: [testhost]: FAILED! => {"changed": false, "msg": "An error occurred (RequestLimitExceeded) when calling the DescribeNatGateways operation (reached max retries: 4): Request limit exceeded.", "resource_actions": ["ec2:DescribeNatGateways"]}`

For example, creating a NAT Gateway can throw this error (see [Shippable result page](https://app.shippable.com/github/ansible-collections/community.aws/runs/1340/summary/console) for further details):
```
- name: Create new NAT gateway with eip allocation-id
    ec2_vpc_nat_gateway:
      subnet_id: "{{ subnet_id }}"
      allocation_id: "{{ allocation_id }}"
      wait: yes
    register: create_ngw
```

I quick workaround is to include an `until` loop as follow:

```
- name: Create new NAT gateway with eip allocation-id
    ec2_vpc_nat_gateway:
      subnet_id: "{{ subnet_id }}"
      allocation_id: "{{ allocation_id }}"
      wait: yes
    register: create_ngw
    retries: 10
    until: create_ngw is not failed
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_vpc_nat_gateway

##### ANSIBLE VERSION
2.10
