### ISSUE TITLE
make ec2_vpc_route_table_info usable on newer regions

### ISSUE THREAD

**Issue by aogier** [ansible-collections/community.aws#380]
##### SUMMARY

Filing this as a feature request as I understand the problem is upstream, anyway, when I try to work with a relatively new region such as `eu-south-1` I get the following error:

```yaml
TASK [get route tables - from] ***************************************************************
fatal: [aws_client]: FAILED! => changed=false 
  msg: >
    Region eu-south-1 does not seem to be available for aws module boto.vpc. 
    If the region definitely exists, you may need to upgrade boto or extend with endpoints_path
```
It is not obvious how to pass this endpoint nor desiderable given that my typical use case will be:

```yaml
- name: get route tables - to
  community.aws.ec2_vpc_route_table_info:
    # something I'm looping on
    region: '{{ item.to.region }}'
    filters:
      # an amazon.aws.ec2_vpc_net_info registered output
      vpc-id: '{{ vpc_to.vpcs[0].vpc_id }}'
  register: routes_to
```
I think we should port this module to boto3, and since I can and I need it I could help on that, but let's coordinate such an effort before I start writing stuff.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_vpc_route_table_info

##### ADDITIONAL INFORMATION

People could happily use newer regions:

```yaml
- name: get route tables - to
  community.aws.ec2_vpc_route_table_info:
    region: eu-south-1
  # <3
  register: I_like_ansible_community_collection
```

Thank you, regards
