### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' error using community.aws.ecs_taskdefinition 

### ISSUE THREAD

**Issue by csamarajeewa** [ansible-collections/community.aws#383]
##### SUMMARY

After upgrading to Ansible 10 I am receiving the following error with community.aws.ecs_taskdefinition module, did not have any issues with Ansible 2.9 using the same inputs.

Error:

    "module_stderr": "Traceback (most recent call last):\n  File 
    \"/REDACTED/AnsiballZ_ecs_taskdefinition.py\", line 102, in <module>\n    _ansiballz_main()\n  
    File \"/REDACTED/AnsiballZ_ecs_taskdefinition.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n 
     File \"/REDACTED/AnsiballZ_ecs_taskdefinition.py\", line 40, in invoke_module\n    
     runpy.run_module(mod_name='ansible_collections.community.aws.plugins.modules.ecs_taskdefinition', init_globals=None, run_name='__main__', alter_sys=True)\n 
      File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n 
       File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n 
        File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  
        File \"/tmp/ansible_community.aws.ecs_taskdefinition_payload_46e9axha/ansible_community.aws.ecs_taskdefinition_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_taskdefinition.py\", 
        line 517, in <module>\n  File \"/tmp/ansible_community.aws.ecs_taskdefinition_payload_46e9axha/ansible_community.aws.ecs_taskdefinition_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_taskdefinition.py\", line 353, 
        in main\nAttributeError: 'str' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.aws.ecs_taskdefinition

##### ANSIBLE VERSION

```paste below

ansible 2.10.4
  config file = None
  configured module search path = ['/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /REDACTED/lib/python3.8/site-packages/ansible
  executable location = /REDACTED/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu Focal

##### STEPS TO REPRODUCE

```yaml

Input into module: 

    "item": {
        "arn_iam_role": "redacted",
        "containers": [
            {
                "environment": [
                    {
                        "name": "REDACTED",
                        "value": "REDACTED"
                    },
                    {
                        "name": "REDACTED",
                        "value": "REDACTED"
                    },
                    {
                        "name": "REDACTED",
                        "value": "REDACTED"
                    },
                    {
                        "name": "REDACTED",
                        "value": "REDACTED"
                    }
                ],
                "essential": REDACTED,
                "image": "docker.io/REDACTED:latest",
                "logConfiguration": {
                    "logDriver": "REDACTED",
                    "options": {
                        "awslogs-create-group": "REDACTED",
                        "awslogs-group": "REDACTED",
                        "awslogs-region": "REDACTED",
                        "awslogs-stream-prefix": "REDACTED"
                    }
                },
                "memoryReservation": REDACTED,
                "name": "REDACTED",
                "portMappings": [
                    {
                        "containerPort": REDACTED
                    }
                ]
            },
            {
                "essential": REDACTED,
                "image": "docker.io/REDACTED:latest",
                "logConfiguration": {
                    "logDriver": "REDACTED",
                    "options": {
                        "awslogs-create-group": "REDACTED",
                        "awslogs-group": "REDACTED",
                        "awslogs-region": "REDACTED",
                        "awslogs-stream-prefix": "REDACTED"
                    }
                },
                "memoryReservation": REDACTED,
                "name": "REDACTED",
                "portMappings": [
                    {
                        "containerPort": REDACTED
                    }
                ]
            },
            {
                "essential": REDACTED,
                "image": "REDACTED:latest",
                "logConfiguration": {
                    "logDriver": "REDACTED",
                    "options": {
                        "awslogs-create-group": "REDACTED",
                        "awslogs-group": "REDACTED",
                        "awslogs-region": "REDACTED",
                        "awslogs-stream-prefix": "REDACTED"
                    }
                },
                "memoryReservation": REDACTED,
                "name": "REDACTED"
            },
            {
                "essential": REDACTED,
                "image": "REDACTED:latest",
                "logConfiguration": {
                    "logDriver": "REDACTED",
                    "options": {
                        "awslogs-create-group": "REDACTED",
                        "awslogs-group": "REDACTED",
                        "awslogs-region": "REDACTED",
                        "awslogs-stream-prefix": "REDACTED"
                    }
                },
                "memoryReservation": REDACTED,
                "name": "REDACTED",
                "portMappings": [
                    {
                        "containerPort": REDACTED,
                        "hostPort": REDACTED
                    }
                ]
            }
        ],
        "name": "REDACTED",
        "task_cpu": REDACTED,
        "task_mem": "REDACTED"
    },

```

##### ACTUAL RESULTS

```paste below

```
