### ISSUE TITLE
iam_role fails to modify attached managed policies

### ISSUE THREAD

**Issue by wimnat** [ansible-collections/community.aws#388]
##### SUMMARY
On first run of iam_role module you can specify the `managed_policy` attribute to attach one or more policies.  If you then change the policies you want to attach the module will report as changed but the old policy will remain attached (no change performed).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iam_role

##### ANSIBLE VERSION

```
ansible 2.11.0.dev0 (devel 564a0fce4a) last updated 2021/02/03 10:42:38 (GMT +000)
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/ansible/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.11.3
  libyaml = True
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Create a role with a managed policy attached.
Change the attached policies
Rerun the play
You will see that your new policies are not attached

```yaml
- name: Test AWS playbook
  hosts: local
  connection: local
  tasks:
    - name: Create an IAM role with attached managed policies
      iam_role:
        name: "my-test-role"
        assume_role_policy_document: "{{ lookup('file', 'files/iam_role_trust_policy_doc.json') }}"
        managed_policy:
          - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        state: present
      register: iam_role
      tags:
          - iam

    - name: Attach a different managed policies to the previously created IAM role
      iam_role:
        name: "my-test-role"
        assume_role_policy_document: "{{ lookup('file', 'files/iam_role_trust_policy_doc.json') }}"
        managed_policy:
          - arn:aws:iam::aws:policy/AdministratorAccess-Amplify
        state: present
      register: iam_role
      tags:
        - iam

```

##### EXPECTED RESULTS
The role's attached policies should match whatever is specified in the module parameter `managed_policy`

##### ACTUAL RESULTS
Ansible runs without error and says "changed" although no changes to managed policies are actually made
