### ISSUE TITLE
S3 community.aws.aws_s3_cors rules error

### ISSUE THREAD

**Issue by csamarajeewa** [ansible-collections/community.aws#404]
##### SUMMARY

Switching to Ansible 2.10 from 2.9 using the collection module community.aws.aws_s3_cors rules I receive the following error trying to add cors rules to an s3 bucket. Previously using the same input arguments it succeeded without issues.

Input Args:

```
    "ansible_loop_var": "item",
    "boto3_version": "1.14.59",
    "botocore_version": "1.17.59",
    "changed": false,
    "invocation": {
        "module_args": {
            "aws_access_key": "REDACTED",
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": "REDACTED",
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "name": "REDACTED",
            "profile": null,
            "region": null,
            "rules": [
                "{'allowed_methods': ['REDACTED', 'REDACTED'], 'allowed_origins': ['REDACTED'], 'allowed_headers': ['REDACTED'], 'max_age_seconds': REDACTED}"
            ],
            "security_token": "REDACTED",
            "state": "present",
            "validate_certs": true
        }
    },

```

Error:

```
ParamValidationError: Parameter validation failed:
Invalid type for parameter CORSConfiguration.CORSRules[0], value: {'allowed_methods': ['REDACTED', 'REDACTED'], 'allowed_origins': ['REDACTED'], 'allowed_headers': ['REDACTED'], 'max_age_seconds': REDACTED}, type: <type 'str'>, valid types: <type 'dict'>
```

The problem can be solved by changing rules arg spec to `rules=dict(type='list'),` 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.aws.aws_s3_cors rules

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = None
  configured module search path = ['/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /REDACTED/ansible-venv/ansible10/lib/python3.8/site-packages/ansible
  executable location = /REDACTED/ansible-venv/ansible10/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu Focal

##### STEPS TO REPRODUCE

```yaml

Input Args:
    "ansible_loop_var": "item",
    "boto3_version": "1.14.59",
    "botocore_version": "1.17.59",
    "changed": false,
    "invocation": {
        "module_args": {
            "aws_access_key": "REDACTED",
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": "REDACTED",
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "name": "REDACTED",
            "profile": null,
            "region": null,
            "rules": [
                "{'allowed_methods': ['REDACTED', 'REDACTED'], 'allowed_origins': ['REDACTED'], 'allowed_headers': ['REDACTED'], 'max_age_seconds': REDACTED}"
            ],
            "security_token": "REDACTED",
            "state": "present",
            "validate_certs": true
        }
    },

```

##### ACTUAL RESULTS

```paste below

```
