### ISSUE TITLE
route53 module in v1.4.0 incorrectly flags alias record changes

### ISSUE THREAD

**Issue by mvermaes** [ansible-collections/community.aws#426]
##### SUMMARY

After updating to `community.aws` v1.4.0, using the `route53` module to check an alias record that points to an S3 bucket results in changes being flagged that weren't previously.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

route53

##### ANSIBLE VERSION
```paste below
ansible 2.10.5
  config file = /rw/data/repos/infra/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/share/virtualenvs/infra-tUXqHdZz/lib/python3.8/site-packages/ansible
  executable location = /home/user/.local/share/virtualenvs/infra-tUXqHdZz/bin/ansible
  python version = 3.8.7 (default, Jan 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

##### CONFIGURATION
```paste below
DEFAULT_GATHER_TIMEOUT(/rw/data/repos/infra/ansible/ansible.cfg) = 60
DEFAULT_HOST_LIST(/rw/data/repos/infra/ansible/ansible.cfg) = ['/rw/data/repos/infra/ansible/hosts']
DEFAULT_MANAGED_STR(/rw/data/repos/infra/ansible/ansible.cfg) = Ansible managed file, manual changes will be overwritten
INVENTORY_ENABLED(/rw/data/repos/infra/ansible/ansible.cfg) = ['aws_ec2', 'host_list', 'script', 'auto', 'yaml', 'ini', 'toml']
```

##### OS / ENVIRONMENT
- Ansible host: Fedora 32
- boto: 2.49.0
- boto3: 1.16.49
- botocore: 1.19.49

##### STEPS TO REPRODUCE

- Create these three files:
```ini
# Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
ansible-base = "*"
boto3 = "*"
boto = "*"
```

```yaml
# requirements.yml 
---
collections:
  - name: amazon.aws
  - name: community.aws
  - name: community.general
```

```yaml
# route53_alias_ansible.yml 
---
- hosts: 127.0.0.1
  connection: local
  become: no

  tasks:
    - community.aws.route53:
        state: present
        zone: <our domain>
        record: <our domain>
        type: A
        value: s3-website-ap-southeast-1.amazonaws.com.
        alias: yes
        alias_hosted_zone_id: Z3O0J2DXBE1FTB
        overwrite: yes
```
- With a pre-existing domain (`<our domain>` in example above) configured with an alias record at apex, pointing to an S3 bucket (per [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-custom-domain-walkthrough.html#root-domain-walkthrough-add-record-to-hostedzone)), and files as per above, run these commands:
```
pipenv install
pipenv run ansible-galaxy collection install -r requirements.yml -f
pipenv run ansible-playbook route53_alias_ansible.yml --check --diff
```

##### EXPECTED RESULTS
```
TASK [community.aws.route53] ************************************************************
ok: [127.0.0.1]
```

##### ACTUAL RESULTS
```
TASK [community.aws.route53] *************************************************************
--- before
+++ after
@@ -5,5 +5,11 @@
         "HostedZoneId": "Z3O0J2DXBE1FTB"
     },
     "Name": "<our domain>.",
+    "ResourceRecords": [
+        {
+            "Value": "s3-website-ap-southeast-1.amazonaws.com."
+        }
+    ],
+    "TTL": 3600,
     "Type": "A"
 }

changed: [127.0.0.1]
```
Reverting to `community.aws` 1.3.0 (leaving `amazon.aws` on 1.4.0) gets the expected results again.

_(Edit 20210302: Add boto to Pipfile - inadvertently removed when trying to create minimal Pipfile. Boto is required to run the listed playbook under version 1.3.0)_
