### ISSUE TITLE
ecs_taskdefinition idempotency fails for containerDefinition secrets

### ISSUE THREAD

**Issue by Alex-Richman** [ansible-collections/community.aws#45]
#18 ### SUMMARY
ecs_taskdefinition idempotency checks fail if `secrets` are supplied in a containerDefinition.

This appears to be because boto3 doesn't actually return the secrets in `describe_task_definition`, so the `_right_has_values_of_left` fails.

Can't really be fixed in Ansible until boto3 is updated (I've raised it with AWS), but useful to have this bug here with the details.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ecs_taskdefinition

##### STEPS TO REPRODUCE
```yaml
ecs_taskdefinition:
  state: present
  force_create: no
  ...
  containers:
    ...
    - name: ...
      secrets: ...
```

##### EXPECTED RESULTS
An ecs_taskdefinition call with the same parameters should correctly validate that a task definition revision already exists with the same configuration.

##### ACTUAL RESULTS
An ecs_taskdefinition with the same parameters (but including secrets config in a containerDefinition) always returned CHANGED.
