### ISSUE TITLE
rds_instance module should support adding IAM roles

### ISSUE THREAD

**Issue by nsushkin** [ansible-collections/community.aws#464]
##### SUMMARY
AWS supports adding IAM roles to RDS instance. It is required for an RDS instance to be able to access an S3 bucket.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
rds_instance

##### ADDITIONAL INFORMATION
AWS CLI supports this via
https://docs.aws.amazon.com/cli/latest/reference/rds/add-role-to-db-instance.html

Adding S3 integration to RDS is described in 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/oracle-s3-integration.html#oracle-s3-integration.preparing

There is an article on Stack Overflow describing a workaround with plays using AWS CLI to do this
https://stackoverflow.com/questions/63010540/attaching-iam-role-to-aws-rds-instance-with-ansible

I think most people would set this up when creating a new RDS instance, so it would make sense
to add this functionality to the rds_instance module instead of making another module.

Since AWS CLI takes feature-name and role-arn arguments, perhaps the usage could be as follows:
```yaml
rds_instance:
  db_instance_identifier: 'test-instance'
  iam_roles:
    - role_arn: 'arn:aws:iam::111122223333:role/rds-s3-integration-role'
      feature_name: 'S3_INTEGRATION'
```
