### ISSUE TITLE
ec2.py duplicate security_groups returns bad error message when no vpc specified.

### ISSUE THREAD

**Issue by rob42** [ansible-collections/community.aws#507]
##### SUMMARY
Under certain circumstances ec2.py reports "The following group names are not valid:..." when the real problem is duplicate names were found. This send the user into the mire that is `force_valid_group_names`, never to return, at least not sane anyway...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2.py

##### ANSIBLE VERSION
```
ansible 2.10.7

```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = True
ANSIBLE_SSH_ARGS(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no
ANSIBLE_SSH_CONTROL_PATH(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = %(directory)s/ssh-%%C
DEFAULT_HOST_LIST(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = ['/home/robert/gitrep/cp_ansible/inventory']
DEFAULT_MANAGED_STR(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_PRIVATE_KEY_FILE(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = /home/robert/.ssh/CP-D2A-DEV-20190509
DEFAULT_REMOTE_USER(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = ubuntu
DEFAULT_ROLES_PATH(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = ['/home/robert/gitrep/cp_ansible/roles/internal', '/home/robert/gitrep/cp_ansible/roles/external', '/etc/a
DEFAULT_VAULT_PASSWORD_FILE(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = /home/robert/vault/vpass-dev-d2a
INVENTORY_ENABLED(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = ['auto']
TRANSFORM_INVALID_GROUP_CHARS(/home/robert/gitrep/cp_ansible/plays/ansible-devd2a.cfg) = never

```

##### OS / ENVIRONMENT
ubuntu linux 20.04

##### STEPS TO REPRODUCE
On AWS you will need two security groups in different VPC's, with the same names
Using `ec2_instance` update the security groups with ansible, but do not include a `vpc_id` or a `vpc_subnet_id`
(Apologies this is in a loop)
```yaml
- name: Update instances.
  ec2_instance:
    region: "{{ vpc.region }}"
    filters:
      "instance_id": "{{item}}"
      "tag:Name": "{{ outer_item.0.instance_tags.Name }}"
      "tag:Zone": "{{ outer_item.0.instance_tags.Zone }}"
      instance-state-name: 
        - running
    security_groups: "{{ outer_item.0.groups }}"
    # vpc_subnet_id: "{{ outer_item.1.subnets|map(attribute='id')|list|random }}"
  register: ec2_results_inner
  with_items: "{{existing_instances.instances|list |map(attribute='instance_id') | list}}"
```
this fails in line 588, in get_ec2_security_group_ids_from_names\nValueError: The following group names are not valid: ....outer_item.0.groups names....\n"

Since the names have hyphens  this sent me on the path of `force_valid_group_names`, and why it appeared not to work. 
The real error is the code fails to match all the group names (as their are duplicates) and then puts out an unhelpful message.

```yaml
- name: Update instances.
  ec2_instance:
    region: "{{ vpc.region }}"
    filters:
      "instance_id": "{{item}}"
      "tag:Name": "{{ outer_item.0.instance_tags.Name }}"
      "tag:Zone": "{{ outer_item.0.instance_tags.Zone }}"
      instance-state-name: 
        - running
    security_groups: "{{ outer_item.0.groups }}"
    vpc_subnet_id: "{{ outer_item.1.subnets|map(attribute='id')|list|random }}"
  register: ec2_results_inner
  with_items: "{{existing_instances.instances|list |map(attribute='instance_id') | list}}"
```
This works as expected. All groups are matched so in line 587 `len(still_unmatched)` ==0

##### EXPECTED RESULTS
When matching group names all duplicates should be matched too. Even though the duplicates  may be in other VPC's the name is still valid input for the instance since at least one of the duplicate groups are in the same vpc. Alternatively output a more useful error message

##### ACTUAL RESULTS

As above the error message is output and (very) unhelpful.
```paste below

```
