### ISSUE TITLE
ec2_instance fails if there is no default vpc and no vpc_subnet_id specified

### ISSUE THREAD

**Issue by nerijus** [ansible-collections/community.aws#511]
##### SUMMARY

There is only one VPC in the region, but it is not default (Default VPC: No). I.e. there is no default VPC at all in this region.
I try to create ec2 instance by using:
```
- name: Create a new ec2 instance
  ec2_instance:
    name: "{{ route53_hostname }}"
    key_name: "{{ key_name }}"
    security_group: unhindered
    instance_type: "{{ size }}"
    image_id: 'ami-0d2f2...'
    region: "{{ region }}"
    availability_zone : "{{ availability_zone }}"
    volumes: "{{ volumes }}"
```
It fails with:
```
 File "/tmp/ansible_ec2_instance_payload_c9xfa938/ansible_ec2_instance_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_instance.py", line 1409, in get_default_subnet
TypeError: 'NoneType' object is not subscriptable

```
The docs at `https://docs.ansible.com/ansible/latest/collections/community/aws/ec2_instance_module.html#parameter-availability_zone` say that availability zone is useful if not specifying the vpc_subnet_id parameter.
But it does not work in my case. When I specify `vpc_subnet_id`, it works.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

  ec2_instance
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
