### ISSUE TITLE
elb_target_group support for application-based sticky session cookies

### ISSUE THREAD

**Issue by heytrav** [ansible-collections/community.aws#513]
##### SUMMARY

AWS Application load balancers now appear to support application-based cookies in addition to the standard load balancer generated cookie.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/sticky-sessions.html
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

elb_target_group
##### ADDITIONAL INFORMATION

The application based cookie has a duration attribute just as the load balancer generated cookie does. It is also required to assign a name to the cookie that is specific to the target group.

```yaml
- name: Modify the target group with a custom health check
  community.aws.elb_target_group:
    name: mytargetgroup
    protocol: http
    port: 80
    vpc_id: vpc-01234567
    health_check_protocol: http
    health_check_path: /health_check
    health_check_port: 80
    successful_response_codes: 200
    health_check_interval: 15
    health_check_timeout: 3
    healthy_threshold_count: 4
    unhealthy_threshold_count: 3
    stickiness_enabled: yes
    stickiness_lb_cookie_duration: 86400
    stickiness_application_cookie_name: my_application_cookie
    state: present
```
