### ISSUE TITLE
community.aws.route53 state:get - return value differs between 2.10.7 and 2.10.6

### ISSUE THREAD

**Issue by dseeley** [ansible-collections/community.aws#523]
##### SUMMARY
With Ansible 2.10.7, the return value (within the `set` parameter) from the community.aws.route53 module run with `state: get` does not correspond to expected values defined in documentation.  Works as documented in Ansible 2.9.7. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.aws.route53

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
  config file = /homedir/modpath/ansible.cfg
  configured module search path = ['/homedir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/homedir/modpath/ansible.cfg) = -o 'UserKnownHostsFile=/dev/null' -o 'ControlMaster=auto' -o 'ControlPersist=60s'
ANSIBLE_SSH_CONTROL_PATH_DIR(/homedir/modpath/ansible.cfg) = /tmp/.ansible/cp
ANSIBLE_SSH_RETRIES(/homedir/modpath/ansible.cfg) = 5
DEFAULT_FORCE_HANDLERS(/homedir/modpath/ansible.cfg) = True
DEFAULT_FORKS(/homedir/modpath/ansible.cfg) = 50
DEFAULT_ROLES_PATH(/homedir/modpath/ansible.cfg) = ['/homedir/modpath/roles']
DEFAULT_VAULT_PASSWORD_FILE(/homedir/modpath/ansible.cfg) = /homedir/modpath/.vaultpass-client.py
HOST_KEY_CHECKING(/homedir/modpath/ansible.cfg) = False
INTERPRETER_PYTHON(/homedir/modpath/ansible.cfg) = auto
TRANSFORM_INVALID_GROUP_CHARS(/homedir/modpath/ansible.cfg) = ignore

```

##### OS / ENVIRONMENT

+ Ubuntu 20.04.2 LTS
+ Python 3.8.5
+ Ansible installed in new OS with pip

##### STEPS TO REPRODUCE

```yaml
    - community.aws.route53:
        state: "get"
        zone: "intensible.com"
        record: "test.intensible.com"
        type: "A"
      register: r__route53_a

    - debug: msg={{r__route53_a}}
```

##### EXPECTED RESULTS

```yaml
    "msg": {
        "changed": false,
        "failed": false,
        "nameservers": [
            "ns-324.awsdns-40.com.",
            "ns-852.awsdns-42.net.",
            "ns-1059.awsdns-04.org.",
            "ns-1680.awsdns-18.co.uk."
        ],
        "set": {
            "alias": false,
            "failover": null,
            "health_check": null,
            "hosted_zone_id": "xxxx",
            "identifier": null,
            "record": "test.intensible.com.",
            "region": null,
            "ttl": "300",
            "type": "A",
            "value": "10.10.10.10",
            "values": [
                "10.10.10.10"
            ],
            "weight": null,
            "zone": "intensible.com."
        }
    }
```

##### ACTUAL RESULTS

```yaml
Loading collection amazon.aws from /usr/local/lib/python3.8/dist-packages/ansible_collections/amazon/aws
Using module file /usr/local/lib/python3.8/dist-packages/ansible_collections/community/aws/plugins/modules/route53.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dougal
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "alias": null,
            "alias_evaluate_target_health": false,
            "alias_hosted_zone_id": null,
            "aws_access_key": "xxxx",
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "failover": null,
            "health_check": null,
            "hosted_zone_id": null,
            "identifier": null,
            "overwrite": null,
            "private_zone": false,
            "profile": null,
            "record": "test.intensible.com",
            "region": null,
            "retry_interval": 500,
            "security_token": null,
            "state": "get",
            "ttl": 3600,
            "type": "A",
            "validate_certs": true,
            "value": null,
            "vpc_id": null,
            "wait": false,
            "wait_timeout": 300,
            "weight": null,
            "zone": "intensible.com"
        }
    },
    "nameservers": [
        "ns-324.awsdns-40.com",
        "ns-852.awsdns-42.net",
        "ns-1059.awsdns-04.org",
        "ns-1680.awsdns-18.co.uk"
    ],
    "set": {
        "Name": "test.intensible.com.",
        "ResourceRecords": [
            {
                "Value": "10.10.10.10"
            }
        ],
        "TTL": 300,
        "Type": "A"
    }
}

TASK [debug] ***********************************************************************************************************
task path: /homedir/modpath/test5.yml:42
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "nameservers": [
            "ns-324.awsdns-40.com",
            "ns-852.awsdns-42.net",
            "ns-1059.awsdns-04.org",
            "ns-1680.awsdns-18.co.uk"
        ],
        "set": {
            "Name": "test.intensible.com.",
            "ResourceRecords": [
                {
                    "Value": "10.10.10.10"
                }
            ],
            "TTL": 300,
            "Type": "A"
        }
    }
}
```
