### ISSUE TITLE
community.aws.route53_info query:record_sets - type and max_items ignored on all 2.10 versions

### ISSUE THREAD

**Issue by tamirhad** [ansible-collections/community.aws#529]
##### SUMMARY
on every 2.10.x ansible-base version, when using `community.aws.route53_info` module with `query:record_sets`:
* `max_items` is ignored.
* `type` is ignored.
same issue also mentioned here https://github.com/ansible-collections/community.aws/issues/523
under 2.9.x versions everything works fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.aws.route53_info
plugins/modules/route53_info.py

##### ANSIBLE VERSION
tested with every version under 2.10
but for this exmaple:

```paste below
ansible 2.10.7
  config file = None
  configured module search path = ['/Users/tamir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tamir/opt/anaconda3/envs/django/lib/python3.9/site-packages/ansible
  executable location = /Users/tamir/opt/anaconda3/envs/django/bin/ansible
  python version = 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20) [Clang 11.0.1 ]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed produce no output
```

##### OS / ENVIRONMENT

* brand new environment on macos, ubuntu18

##### STEPS TO REPRODUCE

```yaml
- name: Get alias
   route53_facts:
     query: record_sets
     hosted_zone_id: "{{host_zone_id}}"
     start_record_name: "{{ dns.records[0].record }}"
     type: "A"
     max_items: 1
   register: record_sets
```

##### EXPECTED RESULTS

single A record due to max_items:1 with type: "A"

##### ACTUAL RESULTS

all records with every type under the host_zone.
cant paste the actual results due to privacy, but its easy to reproduce.

```paste below

```
