### ISSUE TITLE
adding tags and propagateTags to community.aws.ecs_service

### ISSUE THREAD

**Issue by tamirhad** [ansible-collections/community.aws#541]
##### SUMMARY
my main goal is to use propagateTags(tags inheritance to tasks)
In order to use propagateTags feature - (https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html)
the service needs to be created with tags at the creation time, and not by invoking TagResource API action later on.
my suggestion is adding dict of tags at the creation time and propagateTags

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.aws.ecs_service

##### ADDITIONAL INFORMATION

```yaml
- community.aws.ecs_service:
    state: present
    name: test-service
    cluster: test-cluster
    task_definition: test-task-definition
    desired_count: 3
    tags: 
      exmaple1: 1
      example2: 2
    propagateTags: SERVICE
```
