### ISSUE TITLE
ec2_scaling_policy - Add support for TargetTrackingScaling policies

### ISSUE THREAD

**Issue by anjo-swe** [ansible-collections/community.aws#544]
##### SUMMARY

Allow creation of `TargetTrackingScaling` policies using `ec2_scaling_policy` module

###### References
* https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html
* https://docs.aws.amazon.com/cli/latest/reference/autoscaling/put-scaling-policy.html
* https://github.com/awsdocs/amazon-ec2-auto-scaling-user-guide/blob/master/doc_source/as-scaling-target-tracking.md

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_scaling_policy

##### ADDITIONAL INFORMATION

Feature would be used similar to how you can currently create `SimpleScaling` (default) & `StepScaling` policies. The module would need a similar if-statement that was added for `StepScaling` - https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/ec2_scaling_policy.py#L275-L290

```yaml
- name: Target tracking scaling policy
  community.aws.ec2_scaling_policy:
    state: present
    region: US-XXX
    name: "target-tracking-scaling-policy"
    policy_type: TargetTrackingScaling
    target_tracking_configuration:
      target_value: 40.0
      predefined_metric_specification:
        predefined_metric_type: ASGAverageCPUUtilization
    asg_name: "application-asg"

```
