### ISSUE TITLE
Failing to create new Route53 alias record.

### ISSUE THREAD

**Issue by naesheim** [ansible-collections/community.aws#545]
##### SUMMARY
Failing to create an alias record for Route53

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Route53

##### ANSIBLE VERSION
2.10.6

##### OS / ENVIRONMENT
OSX

##### STEPS TO REPRODUCE
```
- hosts: localhost
  tasks:
    - name: add new.mydomain.io
      community.aws.route53:
        zone: mydomain.io
        state: present
        record: new.mydomain.io
        type: A
        value: 
          - <my.cloudfront.net>
        alias: True
        alias_hosted_zone_id : zone_id
```

##### EXPECTED RESULTS
Alias A record created. 

##### ACTUAL RESULTS

_Values in error message are changed_

```
"error": {
        "code": "InvalidInput",
        "message": "Invalid request: Expected exactly one of [AliasTarget, all of [TTL, and ResourceRecords], or TrafficPolicyInstanceId], but found more than one in Change with [Action=CREATE, Name=new.mydomain.io., Type=A, SetIdentifier=null]",
        "type": "Sender"
    },

```
When alias : True, I would expect TTL and ResourceRecords be removed from [resource_records_set](https://github.com/ansible-collections/community.aws/blob/44a9d82c74a82515fb2ae4fd967bd8da46531227/plugins/modules/route53.py#L563). 
TrafficPolicyInstanceId seems to be outside my control.

Hard coding values into /plugins/modules/route53.py and running as python script works.

In advance, Thanks:)
