### ISSUE TITLE
aws_eks_nodegroup - Add support for creating EKS managed nodegroups

### ISSUE THREAD

**Issue by gamunu** [ansible-collections/community.aws#549]
##### SUMMARY
New module for handling EKS managed node groups

References

- https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Client.create_nodegroup
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Client.delete_nodegroup
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Waiter.NodegroupActive
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Waiter.NodegroupDeleted
- https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
New component - `aws_eks_nodegroup` 

##### ADDITIONAL INFORMATION
EKS managed node groups automate the provision and lifecycle management of nodes for EKS clusters. Having this module complements the `aws_eks_cluster` module. Currently the only way to provision managed node group using a cloudformation stack or using command module as a wrapper around the eksctl or aws cli.

```yaml
- name: create eks nodegroup
  community.aws.aws_eks_nodegroup:
    cluster_name: 'my-eks-cluster'
    nodegroup_name: 'cluster-ng-0'
    min_size: 1
    max_size: 10
    desired_capacity: 5
    disk_size: 500
    ami_type: 'AL2_x86_64'
    remote_access:
      ec2_ssh_key: 'sshkey'
      source_security_groups: [ 'sg-abcd1234', 'sg-1a2b3c4d' ]
    node_role: 'arn:aws:iam::1234567890:role/noderole'
    labels:
      - environment: production
        availablity_zone: 'us-east-1'
    tags:
      - environment: production
        cluster: 'abcs1234'
     launch_template:
        version: '1'
        launch_template_name: 'lt-example'
        launch_template_id: 'lt-123456'
     capacity_type: 'ON_DEMAND'
     version: '1.19.6'
     release_version: '1.19.6-20210414'
```
