### ISSUE TITLE
Support tagging for AWS IAM managed policies

### ISSUE THREAD

**Issue by celik0311** [ansible-collections/community.aws#566]
##### SUMMARY

Add the ability to tag managed AWS IAM policies

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

iam_managed_policy

##### ADDITIONAL INFORMATION

AWS supports tagging [Managed IAM policies](https://docs.aws.amazon.com/cli/latest/reference/iam/tag-policy.html), we should be able to do that from the managed IAM policy module.

```yaml
- name: Create IAM Managed Policy
  community.aws.iam_managed_policy:
...
    tags:
      foo: bar
```
