### ISSUE TITLE
[elb_application_lb]: Create new ApplicationLoadBalancer fails

### ISSUE THREAD

**Issue by alinabuzachis** [ansible-collections/community.aws#572]
##### SUMMARY

AlicationLoadBalancer creation fails

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

elb_application_lb

##### STEPS TO REPRODUCE

```yaml
  - name: creating an ELB with dualstack ip adress type
    elb_application_lb:
      name: "{{ elb_name }}"
      subnets: "{{ elb_subnets }}"
      security_groups: "{{ sec_group.group_id }}"
      state: present
      listeners:
        - Protocol: HTTP
          Port: 80
          DefaultActions:
            - Type: forward
              TargetGroupName: "{{ tg_name }}"
      ip_address_type: "dualstack"
    register: elb
```
throws

```
AttributeError: 'ApplicationLoadBalancer' object has no attribute 'modify_ip_address_type'
fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/alinabuzachis/.ansible/tmp/ansible-tmp-1620419678.548963-23176-129735685230990/AnsiballZ_elb_application_lb.py\", line 116, in <module>\n    _ansiballz_main()\n  File \"/Users/alinabuzachis/.ansible/tmp/ansible-tmp-1620419678.548963-23176-129735685230990/AnsiballZ_elb_application_lb.py\", line 108, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/alinabuzachis/.ansible/tmp/ansible-tmp-1620419678.548963-23176-129735685230990/AnsiballZ_elb_application_lb.py\", line 54, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.aws.plugins.modules.elb_application_lb', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Users/alinabuzachis/anaconda3/envs/py38/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Users/alinabuzachis/anaconda3/envs/py38/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Users/alinabuzachis/anaconda3/envs/py38/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_elb_application_lb_payload_1wy3uiva/ansible_elb_application_lb_payload.zip/ansible_collections/community/aws/plugins/modules/elb_application_lb.py\", line 681, in <module>\n  File \"/tmp/ansible_elb_application_lb_payload_1wy3uiva/ansible_elb_application_lb_payload.zip/ansible_collections/community/aws/plugins/modules/elb_application_lb.py\", line 675, in main\n  File \"/tmp/ansible_elb_application_lb_payload_1wy3uiva/ansible_elb_application_lb_payload.zip/ansible_collections/community/aws/plugins/modules/elb_application_lb.py\", line 571, in create_or_update_elb\nAttributeError: 'ApplicationLoadBalancer' object has no attribute 'modify_ip_address_type'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

While
```yaml
    - name: create load balancer
      elb_application_lb:
        name: "{{ ecs_load_balancer_name }}"
        state: present
        scheme: internal
        security_groups: '{{ setup_sg.group_id }}'
        subnets: "{{ subnets }}"
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: "{{ ecs_target_group_name }}1"
          - Protocol: HTTP
            Port: 81
            DefaultActions:
              - Type: forward
                TargetGroupName: "{{ ecs_target_group_name }}2"
```
throws
```
AttributeError: 'ApplicationLoadBalancer' object has no attribute 'get_elb_ip_address_type'
fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/alinabuzachis/.ansible/tmp/ansible-tmp-1620408468.4528651-11236-102670838947037/AnsiballZ_elb_application_lb.py\", line 116, in <module>\n    _ansiballz_main()\n  File \"/Users/alinabuzachis/.ansible/tmp/ansible-tmp-1620408468.4528651-11236-102670838947037/AnsiballZ_elb_application_lb.py\", line 108, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/alinabuzachis/.ansible/tmp/ansible-tmp-1620408468.4528651-11236-102670838947037/AnsiballZ_elb_application_lb.py\", line 54, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.aws.plugins.modules.elb_application_lb', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Users/alinabuzachis/anaconda3/envs/py38/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Users/alinabuzachis/anaconda3/envs/py38/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Users/alinabuzachis/anaconda3/envs/py38/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_elb_application_lb_payload_52z9b36_/ansible_elb_application_lb_payload.zip/ansible_collections/community/aws/plugins/modules/elb_application_lb.py\", line 681, in <module>\n  File \"/tmp/ansible_elb_application_lb_payload_52z9b36_/ansible_elb_application_lb_payload.zip/ansible_collections/community/aws/plugins/modules/elb_application_lb.py\", line 675, in main\n  File \"/tmp/ansible_elb_application_lb_payload_52z9b36_/ansible_elb_application_lb_payload.zip/ansible_collections/community/aws/plugins/modules/elb_application_lb.py\", line 594, in create_or_update_elb\nAttributeError: 'ApplicationLoadBalancer' object has no attribute 'get_elb_ip_address_type'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
