### ISSUE TITLE
ec2_vpc_peer creates new peering connection when Accepter and Requester are reversed

### ISSUE THREAD

**Issue by sszwed** [ansible-collections/community.aws#580]
##### SUMMARY

When the Requester and Accepter are reversed, the module is creating a new VPC peering connection. There is no way to accept this connection because it already exists.
The issue appeared in version `1.5.0`, and before this version, it worked fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_vpc_peer

##### ANSIBLE VERSION

```paste below
ansible 2.10.9
  config file = /Users/x/work/repo/ansible.cfg
  configured module search path = ['/Users/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/x/work/repo/venv/lib/python3.9/site-packages/ansible
  executable location = /Users/x/work/repo/venv/bin/ansible
  python version = 3.9.2 (default, Mar 15 2021, 17:37:51) [Clang 12.0.0 (clang-1200.0.32.29)]
```

##### CONFIGURATION

```paste below
DEFAULT_VERBOSITY(env: ANSIBLE_VERBOSITY) = 1
```

##### OS / ENVIRONMENT

My OS is MacOS Bug Sur 11.2.1

##### STEPS TO REPRODUCE

- Create VPC peering connection
- Run module with reversed Requester and Accepter

Note: Module in a version before `1.5.0` are also creating new peering connection when in AWS exists deleted connection with the order like specified in the task, so to test it, you need to request connection which doesn't have deleted connections.

```yaml
- name: Request VPC peerings
  ec2_vpc_peer:
    vpc_id: "{{ vpc_id }}"
    peer_vpc_id: "{{ peer_vpc_id }}"
    peer_region: "{{ peer_region }}"
    peer_owner_id: "{{ peer_owner_id }}"
    state: present
    region: "{{ region }}"
    aws_access_key: "{{ session_credentials.access_key }}"
    aws_secret_key: "{{ session_credentials.secret_key }}"
    security_token: "{{ session_credentials.session_token }}"
  register: vpc_peerings_requested

- name: Accept VPC peering
  ec2_vpc_peer:
    peering_id: "{{ vpc_peerings_requested.peering_id }}"
    state: accept
    region: "{{ peer_region }}"
    aws_access_key: "{{ peer_credentials.access_key }}"
    aws_secret_key: "{{ peer_credentials.secret_key }}"
    security_token: "{{ peer_credentials.session_token }}"
```

##### EXPECTED RESULTS

First task is creating a peering connection, and the second task is failing because the connection already exists

##### ACTUAL RESULTS

All two tasks passes without any changes
