### ISSUE TITLE
RDS Cluster support in module community.aws.rds_snapshot

### ISSUE THREAD

**Issue by txynidakis** [ansible-collections/community.aws#593]
##### SUMMARY

Improve the module community.aws.rds_snapshot to cater for RDS Clusters

##### ISSUE TYPE
- Feature Improvement

##### COMPONENT NAME

community.aws.rds_snapshot

##### ADDITIONAL INFORMATION

The module community.aws.rds_snapshot_info has provisioned the module to use on RDS cluster with the following parameters
* db_cluster_snapshot_identifier
* db_cluster_identifier

The request is to map the cluster parameter from community.aws.rds_snapshot_info to community.aws.rds_snapshot

```yaml
    tasks:
    - name: Create snapshot
      community.aws.rds_snapshot:
        db_cluster_identifier: myrds-cluster
        db_cluster_snapshot_identifier: mytds-custer-snapshot
```

Does an alternative already exist to manage RDS Cluster Snapshots?
