### ISSUE TITLE
ec2_scaling_policy - Region eu-west-2 does not seem to be available for aws module boto.

### ISSUE THREAD

**Issue by gregharvey** [ansible-collections/community.aws#602]
##### SUMMARY
We are using London `eu-west-2`. I made a role to build CloudWatch alarms and scaling policies for a new cluster, tested it in Dublin (`eu-west-1`) and everything worked. Tried it on a client in London and got:

`Region eu-west-2 does not seem to be available for aws module boto.ec2.autoscale. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path`

From what I can tell this means this module is not using boto3, but obsolete boto instead? I'm no Python coder, but that's what Google seems to imply. And I think it must be this module, as we have a complex Ansible stack of roles using various `community.aws` modules and all the others up to this point are happy with the region.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
* ec2_scaling_policy

##### ANSIBLE VERSION

```
ansible 2.9.22
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
no output for --only-changed
```

##### OS / ENVIRONMENT

Debian 10 (Buster) in all cases.

##### STEPS TO REPRODUCE

```yaml
# VARS
_env_type: dev
aws_ec2_autoscale_cluster:
  aws_profile: test
  region: "eu-west-2"
  name: "test-dev-asg"
  asg_scaling_policies: # List of AutoScale policies. See ec2_scaling_policy module docs for options and details.
    - name: "{{ _env_type }}-scale-up-policy"
      policy_type: "SimpleScaling"
      adjustment_type: "ChangeInCapacity"
      adjustment: 2
      adjustment_step: 1 # Only used when adjustment_type is PercentChangeInCapacity.
      cooldown: 300

# TASK
- name: Create simple scaling AutoScale policies.
  community.aws.ec2_scaling_policy:
    profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
    region: "{{ aws_ec2_autoscale_cluster.region }}"
    state: "present"
    name: "{{ item.name }}-{{ item.policy_type }}"
    adjustment_type: "{{ item.adjustment_type }}"
    asg_name: "{{ aws_ec2_autoscale_cluster.name }}"
    scaling_adjustment: "{{ item.adjustment }}"
    min_adjustment_step: "{{ item.adjustment_step }}"
    cooldown: "{{ item.cooldown }}"
  when:
    - aws_ec2_autoscale_cluster.asg_scaling_policies
    - "{{ item.policy_type == 'SimpleScaling' }}"
  register: _aws_ec2_autoscale_cluster_simple_scaling_policies
  with_items: "{{ aws_ec2_autoscale_cluster.asg_scaling_policies }}"
```

Code is public, see:
https://github.com/codeenigma/ce-provision/blob/devel/roles/aws/aws_ec2_autoscale_cluster/tasks/main.yml#L213

##### EXPECTED RESULTS

Obviously I'm expecting it to make a scaling policy in London, just as it does successfully already in Dublin!

##### ACTUAL RESULTS

To follow, need to see if `-vvvv` actually gives us any more results.

```paste below

```
