### ISSUE TITLE
elb_network_lb always shown as changed

### ISSUE THREAD

**Issue by mszumilak** [ansible-collections/community.aws#604]
##### SUMMARY
`elb_network_lb` shows state of LB as `changed` with no changes made.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
elb_nework_lb

##### ANSIBLE VERSION
```
ansible [core 2.11.1] 
  config file = /home/x/ansible.cfg
  configured module search path = ['/home/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/x/venvs/ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /home/x/.ansible/collections
  executable location = /home/x/venvs/ansible/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True

```

##### CONFIGURATION

```
n/a
```

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE

Create NLB and re-run the same task/playbook

```yaml
- name: Create internal NLB
  elb_network_lb:
    name: "my-internal-nlb"
    deletion_protection: True
    subnets: "{{ private_elb_subnets }}"
    scheme: internal
    listeners:
      - Protocol: TCP
        Port: 5555
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ target_group_1_name }}"
      - Protocol: TCP
        Port: 5556
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ target_group_2_name }}"
    state: present
    region: "{{ aws_region }}"

```

##### EXPECTED RESULTS

I'd exect this module to show no changes if there are no changes.

##### ACTUAL RESULTS

Every time I run the playbook the NLB task is shown as `changed`

```paste below
TASK [aws/eks : Create internal NLB] ******************************************
changed: [localhost]
```
