### ISSUE TITLE
AWS Ansible iam_policy: The security token included in the request is invalid

### ISSUE THREAD

**Issue by selvarajendran** [ansible-collections/community.aws#617]
The below list of tasks, I am trying to execute

```
- hosts: localhost
  connection: local
  tasks:
    - name: List s3 buckets
      shell: "aws s3 ls"

    - name: Gather SNI router instance facts
      ec2_instance_info:     
        region: "us-east-1"
        filters:
          "tag:name": "selva"
      register: instances

    - name: Create IAM role
      iam_role:
        name: vpc_dns
        description: Allow Lambda to access AWS services
        region: "us-east-1"
        assume_role_policy_document:
          Version: '2012-10-17'
          Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com

    - name: Create IAM policy for DNS Lambda
      **iam_policy:**
        region: "us-east-1"
        iam_name: vpc_dns
        iam_type: role
        state: present
        policy_name: vpc_dns
        policy_json:
          Version: '2012-10-17'
          Statement:
          - Action: ec2:Describe*
            Effect: Allow
            Resource: "*"
      register: vpc_dns_role
```

I have got the temporary credentials using sts get-session-token and stored the secrets in the default config using below

`aws configure set default.region us-east-1 ; aws configure set aws_access_key_id XXXX ; aws configure set aws_secret_access_key XXXX ; aws configure set aws_session_token XXXX ;`

From the above list of task first 3 got executed successfully, whereas the last one, iam_policy task failed and throws an error as below

```
File "/tmp/ansible_iam_policy_payload_ldb3fV/ansible_iam_policy_payload.zip/ansible/modules/cloud/amazon/iam_policy.py", line 176, in role_action
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/iam/connection.py", line 1314, in list_role_policies
    list_marker='PolicyNames')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto/iam/connection.py", line 102, in get_response
    raise self.ResponseError(response.status, response.reason, body)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "iam_name": "vpc_dns",
            "iam_type": "role",
            "policy_document": null,
            "policy_json": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Action\": \"ec2:Describe*\", \"Resource\": \"*\", \"Effect\": \"Allow\"}]}",
            "policy_name": "vpc_dns",
            "profile": null,
            "region": "us-east-1",
            "security_token": null,
            "skip_duplicates": true,
            "state": "present",
            "validate_certs": true
        }
    },
    **"msg": "The security token included in the request is invalid."**
```
}

**Comment by selvarajendran** [comment]
**Ansible Version**
$ ansible --version

ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]

**Comment by tremble** [comment]
@selvarajendran 

It's not exactly easy to spot, but iam_policy is unfortunately still using the old 'boto' SDK (rather than boto3/botocore) `aws configure` will be dropping the credentials into the wrong location for the old SDK.  Migrating over to boto3 is a "wishlist" item, but takes a significant effort.  Passing credentials directly to the module will work around this.  I know it's not a perfect solution, but it's the best that can be offered right now.

**Comment by selvarajendran** [comment]
@tremble Thanks for the details. I will try with credentials.

**Comment by ansibullbot** [comment]
@selvarajendran: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jillr @s-hertel @sbj-ss @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by markuman** [comment]
You can do this - more or less - elegant using `ini` lookup plugin.

```yml
- name: set up aws connection info
    set_fact:
      aws_connection_info: &aws_connection_info
        aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=default file=~/.aws/credentials') }}"
        aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=default file=~/.aws/credentials') }}"
        security_token: "{{ lookup('ini', 'aws_session_token section=default file=~/.aws/credentials') }}"
        region: eu-central-1
    no_log: True

- name: Create IAM policy for DNS Lambda
  iam_policy:
    <<: *aws_connection_info
    region: "us-east-1"
    iam_name: vpc_dns
    iam_type: role
    state: present
    policy_name: vpc_dns
    policy_json:
      Version: '2012-10-17'
      Statement:
      - Action: ec2:Describe*
        Effect: Allow
        Resource: "*"
  register: vpc_dns_role
```

Optionally change the `default` section when you place your STS tokens in a different profile.
