### ISSUE TITLE
AWS elb_target_group requires protocol, port when state is absent

### ISSUE THREAD

**Issue by rwky** [ansible-collections/community.aws#69]
Issue reported here https://github.com/ansible/ansible/issues/68760 and was asked to be opened here

##### SUMMARY

when trying to delete a target group via elb_target_group it throws
target_type is instance but all of the following are missing: protocol, port.
double checked and eve in the docs it says those are only needed if state is present

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
elb_target_group

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```
ansible 2.9.9
  config file = /home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/ansible.cfg
  configured module search path = ['/home/rowan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rowan/projects/qwertee.com/infrastructure/aws/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/rowan/projects/qwertee.com/infrastructure/aws/ansible/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```
ANSIBLE_NOCOWS(/home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/ansible.cfg) = True
DEFAULT_BECOME(/home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/ansible.cfg) = sudo
DEFAULT_HOST_LIST(/home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/ansible.cfg) = ['/home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/inventory']
DEPRECATION_WARNINGS(/home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/ansible.cfg) = True
HOST_KEY_CHECKING(/home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/ansible.cfg) = False

```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
Ubuntu 20.04

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml
    - name: Delete site target group                                                                                                                                                                              
      elb_target_group:                                                                             
          profile: "{{awsprofile}}"                                                                          
          region: "{{awsregion}}"                                                                        
          name: "{{target_group}}"                                                               
          state: absent   
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->


delete with no error.

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->
```
TASK [Delete site target group] **********************************************************************************************************************************************************************************
task path: /home/rowan/projects/qwertee.com/infrastructure/aws/test-sites/destroy.yml:43
Using module file /home/rowan/projects/qwertee.com/infrastructure/aws/ansible/lib/python3.8/site-packages/ansible/modules/cloud/amazon/elb_target_group.py
Pipelining is enabled.                              
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: rowan                                                                                                                                                            
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'                                
The full traceback is:                                                                                                                                                                                            
  File "/tmp/ansible_elb_target_group_payload_pe6lf4x0/ansible_elb_target_group_payload.zip/ansible/module_utils/basic.py", line 1577, in _check_required_if
    check_required_if(spec, param)                                                                       
  File "/tmp/ansible_elb_target_group_payload_pe6lf4x0/ansible_elb_target_group_payload.zip/ansible/module_utils/common/validation.py", line 275, in check_required_if
    raise TypeError(to_native(msg))
fatal: [localhost]: FAILED! => {                                                                                                                                                                                  
    "changed": false,             
    "invocation": {                                                                                                                                                                                               
        "module_args": {           
            "debug_botocore_endpoint_logs": false,
            "modify_targets": true,
            "name": "site-dev-issue-2690",
            "profile": "qwertee",
            "purge_tags": true,                   
            "region": "eu-west-1", 
            "state": "absent",            
            "stickiness_type": "lb_cookie",
            "tags": {},        
            "target_type": "instance",
            "validate_certs": true,
            "wait": false,                 
            "wait_timeout": 200
        }                             
    },                             
    "msg": "target_type is instance but all of the following are missing: protocol, port, vpc_id"
}              
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/elb_target_group.py`](https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/elb_target_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jillr @s-hertel @tremble @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by brsolomon-deloitte** [comment]
Still present with Ansible 2.9.23.

```yaml
    - name: Destroy target group                                                                                        
      elb_target_group:                                                                                                 
        region: "{{ aws_region }}"                                                                                      
        name: "{{ aws_target_group_name }}-{{ k8s_cluster_id }}"                                                        
        state: absent                                                                                                   
        wait: true 
```

```
TASK [Destroy target group] **************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "target_type is instance but all of the following are missing: protocol, port, vpc_id"}
```
