### ISSUE TITLE
community.aws.route53 TXT record fails with quotation error on comma-separated rua/ruf tags

### ISSUE THREAD

**Issue by t-readyroc** [ansible-collections/community.aws#701]
### Summary

I can create the following record without issue in the AWS console:

```
"v=DMARC1; p=quarantine; fo=1; ri=3600; rua=mailto:comcast@rua.agari.com,mailto:dmarc_rua@emaildefense.proofpoint.com,mailto:dmarc-rua@dmarctest.comcast.net; ruf=mailto:comcast@ruf.agari.com,mailto:dmarc_ruf@emaildefense.proofpoint.com"
```

When I try to create it using community.aws.route53, it fails. It seems to me that something along the way is thinking that the [comma-separated rua/ruf DMARC tags](https://mxtoolbox.com/dmarc/details/dmarc-tags/dmarc-rua) should be separated & surrounded by quotation marks; I'm guessing because of the way that the module accepts multiple comma-separated strings?

### Issue Type

Bug Report

### Component Name

route53

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.12
  config file = /Users/me/.ansible.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/me/.pyenv/versions/3.6.8/envs/ans-2.9/lib/python3.6/site-packages/ansible
  executable location = /Users/me/.pyenv/versions/ans-2.9/bin/ansible
  python version = 3.6.8 (default, Jul 20 2021, 12:37:52) [GCC Apple LLVM 12.0.0 (clang-1200.0.32.21)]
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
Collection              Version
----------------------- -------
amazon.aws              1.5.0  
ansible.posix           1.1.1  
ansible.tower           3.8.1  
community.aws           1.5.0
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/me/.pyenv/versions/3.6.8/envs/ans-2.9/lib/python3.6/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.18.31
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /Users/me/.pyenv/versions/3.6.8/envs/ans-2.9/lib/python3.6/site-packages
Requires: jmespath, s3transfer, botocore
Required-by: 
---
Name: botocore
Version: 1.21.31
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /Users/me/.pyenv/versions/3.6.8/envs/ans-2.9/lib/python3.6/site-packages
Requires: jmespath, urllib3, python-dateutil
Required-by: s3transfer, boto3
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_STDOUT_CALLBACK(/Users/me/.ansible.cfg) = yaml
DEFAULT_VAULT_IDENTITY_LIST(/Users/me/.ansible.cfg) = [my,list]
GALAXY_SERVER_LIST(/Users/me/.ansible.cfg) = ['automation_hub', 'galaxy']
```

### OS / Environment

Mac OS 11.5.2

### Steps to Reproduce

```yaml (paste below)
- name: Manage DNS Zones and Records
  hosts: localhost
  gather_facts: no
  vars:
    provider: aws
    svc_route53_key: <key>
    svc_route53_secret: <secret>
  tasks:
    - name: create records                                                             
      community.aws.route53:                                                           
        aws_access_key: "{{ svc_route53_key }}"                                        
        aws_secret_key: "{{ svc_route53_secret }}"                                     
        zone: "{{ item.0.name }}"                                                      
        record: "{{ item.1.name }}.{{ item.0.name }}"                                  
        type: "{{ item.1.type }}"                                                      
        ttl: "{{ item.1.ttl | default(7200) }}"                                        
        value: "{{ item.1.value }}"                                                    
        state: present                                                                 
        overwrite: yes                                                                 
      loop: "{{ zones | subelements('records', skip_missing=True) }}"  
```

And, the vars file:

```yaml
zones:
  - name: myzone.example
    zone_desc: Main Public Zone
    records:
      - name: _dmarc
        value: '"v=DMARC1; p=quarantine; fo=1; ri=3600; rua=mailto:comcast@rua.agari.com,mailto:dmarc_rua@emaildefense.proofpoint.com,mailto:dmarc-rua@dmarctest.comcast.net; ruf=mailto:comcast@ruf.agari.com,mailto:dmarc_ruf@emaildefense.proofpoint.com"'
        type: TXT
```

### Expected Results

Expected record to be created. Additionally, I created another playbook to grab the value from AWS:

```yaml
# Grab a record from Route53. Run with extravars; e.g.:
# ansible-playbook record_query.yml -e zone_name=<yourZone> -e fqdn_query=<fqdn>

- name: Manage DNS Zones and Records
  hosts: localhost
  gather_facts: no
  vars:
    svc_route53_key: <key>
    svc_route53_secret: <secret>

  tasks:
    - name: retrieve host entries starting with _dmarc
      block:
        - name: grab zone id
          community.aws.route53_zone:
            aws_access_key: "{{ svc_route53_key }}"                                        
            aws_secret_key: "{{ svc_route53_secret }}"  
            zone: "{{ zone_name }}"
          register: AWSINFO
    
        - name: grab Route53 record information
          community.aws.route53_info:
            aws_access_key: "{{ svc_route53_key }}"                                        
            aws_secret_key: "{{ svc_route53_secret }}"  
            type: A
            query: record_sets
            hosted_zone_id: "{{ AWSINFO.zone_id }}"
            start_record_name: "{{ fqdn_query }}"
            max_items: 1
          register: RECORDS

        - debug:
            var: RECORDS.ResourceRecordSets[0]
```

The idea being that I could copy the returned result into my vars file, fixing the issue. The returned result was the same as what I'd already had in my vars file.

### Actual Results

```console (paste below)
  - name: _dmarc
    type: TXT
    value: '"v=DMARC1; p=quarantine; fo=1; ri=3600; rua=mailto:comcast@rua.agari.com,mailto:dmarc_rua@emaildefense.proofpoint.com,mailto:dmarc-rua@dmarctest.comcast.net; ruf=mailto:comcast@ruf.agari.com,mailto:dmarc_ruf@emaildefense.proofpoint.com"'
  msg: 'Failed to update records: An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [Invalid Resource Record: ''FATAL problem: InvalidCharacterString (Value should be enclosed in quotation marks) encountered with ''"v=DMARC1; p=quarantine; fo=1; ri=3600; rua=mailto:comcast@rua.agari.com'''', Invalid Resource Record: ''FATAL problem: InvalidCharacterString (Value should be enclosed in quotation marks) encountered with ''mailto:dmarc_rua@emaildefense.proofpoint.com'''', Invalid Resource Record: ''FATAL problem: InvalidCharacterString (Value should be enclosed in quotation marks) encountered with ''mailto:dmarc-rua@dmarctest.comcast.net; ruf=mailto:comcast@ruf.agari.com'''', Invalid Resource Record: ''FATAL problem: InvalidCharacterString (Value should be enclosed in quotation marks) encountered with ''mailto:dmarc_ruf@emaildefense.proofpoint.com"'''']'
  response_metadata:
    http_headers:
      connection: close
      content-length: '1021'
      content-type: text/xml
      date: Tue, 31 Aug 2021 13:36:03 GMT
      x-amzn-actiontrace: amzn1.tr.63af3ec1-0a60-11ec-83f4-0af642470200.-1.wp5hMF.dcLyHF
      x-amzn-requestid: 5910be91-ea7e-4819-9a82-8db8d4937eea
    http_status_code: 400
    request_id: 5910be91-ea7e-4819-9a82-8db8d4937eea
    retry_attempts: 0
```

You can see in the error above that the rua/ruf entries separated by commas are the ones causing the error.

In fact, changing the vars file to the following allows the playbook to complete without error, but produces an incorrectly formed TXT entry:

working vars format:

```yaml
      - name: _dmarc
        value: '"v=DMARC1; p=quarantine; fo=1; ri=3600; rua=mailto:comcast@rua.agari.com","mailto:dmarc_rua@emaildefense.proofpoint.com","mailto:dmarc-rua@dmarctest.comcast.net; ruf=mailto:comcast@ruf.agari.com","mailto:dmarc_ruf@emaildefense.proofpoint.com"'
        type: TXT
```

Resulting record:

```
dig txt @nameserver _dmarc.example.com

; <<>> DiG 9.10.6 <<>> txt @nameserver _dmarc.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12539
;; flags: qr aa rd; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_dmarc.example.com.		IN	TXT

;; ANSWER SECTION:
_dmarc.example.com.	7200	IN	TXT	"mailto:dmarc-rua@dmarctest.comcast.net; ruf=mailto:comcast@ruf.agari.com"
_dmarc.example.com.	7200	IN	TXT	"mailto:dmarc_rua@emaildefense.proofpoint.com"
_dmarc.example.com.	7200	IN	TXT	"mailto:dmarc_ruf@emaildefense.proofpoint.com"
_dmarc.example.com.	7200	IN	TXT	"v=DMARC1; p=quarantine; fo=1; ri=3600; rua=mailto:comcast@rua.agari.com"
```

As you can see, the rua/ruf tags are split with 2 of the email addresses showing up as separate record values (but not part of an rua/ruf tag).

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/route53.py`](https://github.com/['ansible-collections/amazon.aws', 'ansible-collections/community.aws', 'ansible-collections/community.vmware']/blob/main/plugins/modules/route53.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jillr @jimbydamonk @markuman @s-hertel @tremble @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
`value` is a **list** option (https://docs.ansible.com/ansible/latest/collections/community/aws/route53_module.html#parameter-value). You are passing a string, so Ansible does what it always does in such cases: split the string by comma.

So either pass in a one-element list, like
```yaml
- route53:
    value:
      - "{{ item.1.value }}"
```
or make sure that `item.1.value` is a list and not a string.
