### ISSUE TITLE
iam_role should have 'wait_for' option

### ISSUE THREAD

**Issue by dnmvisser** [ansible-collections/community.aws#710]
### Summary

I have a playbook with two tasks:

```yaml
- iam_role:
    name: myrole
  register: ir1

- lambda:
    name: mylambda
    role: "{{ ir1.arn }}"
```

On the first run the IAM role will get created, but the subsequent lambda task will fail immediately with `The role defined for the function cannot be assumed by Lambda.`

Trial and error shows that it might take anywhere between 5 and 10 seconds for the role to be accessible by Lambda. So if I add this task in between the two others the playbook works:

```
- wait_for:
    timeout: 10
  delegate_to: localhost
```
I've know that several other AWS modules have a `wait` option. I'm suggesting the `iam_role` module would benefit such an option as well.

### Issue Type

Feature Idea

### Component Name

iam_role

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
