### ISSUE TITLE
ec2_instance waits until timeout when creating new EC2 instance

### ISSUE THREAD

**Issue by nicorusti** [ansible-collections/community.aws#736]
### Summary

This was discussed in former [issue 65988](https://github.com/ansible/ansible/issues/65988), closed when the old repo was migrated to this one. 

When I use `ec2_instance` with `wait: yes` when creating a new instance, the task is slower than `ec2`. But from the AWS console, you can see that the instance is fully started. It seems that `ec2_instance` is waiting some sort of timeout, instead of returning when the instance is created.

`ec2_instance` should return as soon as the instance is fully created. 

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.3]
  config file = None
  configured module search path = ['/Users/nic/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nic/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/nic/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/nic/Library/Python/3.9/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 04:31:11) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list | grep community.aws
community.aws                 1.5.0
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /opt/homebrew/lib/python3.9/site-packages
Requires:
Required-by:
---
Name: boto3
Version: 1.16.0
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: botocore, jmespath, s3transfer
Required-by:
---
Name: botocore
Version: 1.19.63
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: urllib3, jmespath, python-dateutil
Required-by: s3transfer, boto3, awscli
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_FORKS(/Users/nic/repos/test-ansible/ansible.cfg) = 100
DEFAULT_HOST_LIST(/Users/nic/repos/test-ansible/ansible.cfg) = ['/Users/nic/repos/test-ansible/inventories']
DEFAULT_REMOTE_USER(/Users/nic/repos/test-ansible/ansible.cfg) = ubuntu
DEFAULT_ROLES_PATH(/Users/nic/repos/test-ansible/ansible.cfg) = ['/Users/nic/repos/test-ansible/roles']
DEFAULT_STDOUT_CALLBACK(/Users/nic/repos/test-ansible/ansible.cfg) = debug
DEFAULT_TIMEOUT(/Users/nic/repos/test-ansible/ansible.cfg) = 20
HOST_KEY_CHECKING(/Users/nic/repos/test-ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/nic/repos/test-ansible/ansible.cfg) = ['ini', 'aws_ec2']
```

### OS / Environment

Mac OS 11.6 Big Sur

### Steps to Reproduce

```yaml (paste below)
      community.aws.ec2_instance:
        region: "us-east-1"
        instance_type: t3.small
        image_id: "ami-03a80f322a6053f85"
        wait: yes
        vpc_subnet_id: "vpc-123456789"
        network: 
          assign_public_ip: yes
          delete_on_termination: yes
        security_group: "sg-1234567"
        ebs_optimized: yes
        volumes:
          - device_name: /dev/sda1
            ebs: 
              volume_size: 20
              delete_on_termination: yes
      register: ec2
```

### Expected Results

I'd expect the task to return as soon as the instance is fully created, not when it times out. 

### Actual Results

Task returns at timeout, while you can see in the AWS console that instances are fully created and running long before the task returns. 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
