### ISSUE TITLE
batch_job_definition - Provide Secrets as a part of the container properties

### ISSUE THREAD

**Issue by prathik457** [ansible-collections/community.aws#745]
### Summary

I am trying to send secrets as a part of the container properties JSON object in AWS Batch Job Definition. I do not see an option to provide secrets. Am I missing something here? If not, can this be added?

### Issue Type

Feature Idea

### Component Name

aws_batch_job_definition

### Additional Information

```yaml (paste below)

- hosts: localhost
  gather_facts: no
  vars:
    state: present
  tasks:
- name: My Batch Job Definition
  community.aws.aws_batch_job_definition:
    job_definition_name: My Batch Job Definition
    state: present
    type: container
    parameters:
      Param1: Val1
      Param2: Val2
    image: <Docker Image URL>
    vcpus: 1
    memory: 512
    secrets:
      - name: secret1
        value: secret1
      - name: secret2
        value: secret2
    command:
      - python
      - run_my_script.py
      - arg1
    job_role_arn: <Job Role ARN>
    attempts: 3
  register: job_definition_create_result
- name: show results
  ansible.builtin.debug: var=job_definition_create_result

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
