### ISSUE TITLE
cloudfront_functions

### ISSUE THREAD

**Issue by nick-zh** [ansible-collections/community.aws#750]
### Summary

It would be great to have support for cloudfront functions. Right now you can only specify lambdas for viewer requests, etc.

### Issue Type

Feature Idea

### Component Name

cloudfront_functions

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by shawnbot** [comment]
For anyone else blocked by this, I did figure out a workaround for at least the _association_ of existing CloudFront functions with a distribution's cache behavior. The `cloudfront_distribution` module doesn't validate unrecognized parameters in cache behaviors, so you can pass `function_associations` to either `default_cache_behaviors` or one of the `cache_behaviors` entries. The trick is that you have to conform to the AWS API's [`FunctionAssociations` schema](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_FunctionAssociations.html), which involves some awkward YAML:

```yaml
- name: CloudFront distribution
  community.aws.cloudfront_distribution:
    # ... distribution config
    default_cache_behavior:
      # ... cache behavior config
      function_associations:
        # must match the length of the items list
        quantity: 1
        items:
          # "viewer-request" or "viewer-response"
          - event_type: viewer-request
            # "function_a_r_n" is transformed to "FunctionARN"
            function_a_r_n: arn:aws:cloudfront::{{ aws_account_id }}:function/{{ cf_function_name }}
```
