### ISSUE TITLE
Module elb_classic_lb_info does return noting unless names are given

### ISSUE THREAD

**Issue by stefanhorning** [ansible-collections/community.aws#754]
### Summary

When running the  elb_classic_lb_info module it used to return all classic ELBs for the given account region, as the documentation still states for latest Ansible, see https://docs.ansible.com/ansible/latest/collections/community/aws/elb_classic_lb_info_module.html

> List of ELB names to gather information about. Pass this option to gather information about a set of ELBs, otherwise, all ELBs are returned.

But this holds no longer true. If no name is provided nothing is returned. When looing at the code this is quite obvious why. As name defaults to an empty list and the list method iterates over the list of names, which does nothing when empty, see https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/elb_classic_lb_info.py#L160 

When passing in a name it will return info just fine.

### Issue Type

Bug Report

### Component Name

community.aws.elb_classic_lb_info

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.5] 
  config file =./ansible.cfg
  configured module search path = ['./library', '~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.local/lib/python3.9/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/.local/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
  jinja version = 3.0.1
  libyaml = True

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
# ~/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
amazon.aws           1.5.0  
ansible.posix        1.3.0  
community.aws        1.5.0  
community.general    3.6.0  
community.postgresql 1.4.0  
community.rabbitmq   1.1.0  
```

### Steps to Reproduce

```yaml (paste below)
    - name: Get ELBs information for classic loabalancers
      community.aws.elb_classic_lb_info:
      register: all_classic_elbs

    - name: Output ELB infos
      ansible.builtin.debug:
        var: all_classic_elbs
```

### Expected Results

List of ELBs in `all_classic_elbs.elbs`

### Actual Results

```console (paste below)
ok: [localhost] => {
    "all_classic_elbs": {
        "changed": false,
        "elbs": [],
        "failed": false
    }
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by stefanhorning** [comment]
A taks like 

```yaml
    - name: Get ELBs information for classic loabalancers
      community.aws.elb_classic_lb_info:
        names:
          - My-Existing-Loadbalancer
      register: all_classic_elbs
```

Returns results just fine
