### ISSUE TITLE
Add AWS ECS Capacity Provider Strategy Support

### ISSUE THREAD

**Issue by gregharvey** [ansible-collections/community.aws#770]
### Summary

Migrated from https://github.com/ansible/ansible/issues/67997 (it doesn't seem to have made it over automatically)

Add support for AWS ECS Cluster Capacity Provider Strategy configuration.

Additional note, I noticed this because I was creating a cluster to use with the GitLab CI Fargate driver and started getting `The platform version must be null when specifying an EC2 launch type.` when trying to launch a job. It worked with a manually created Cluster and Task Definition, so I looked closely and found the difference was the manually created cluster had two Capacity Providers and the Ansible created one had none, nor can you manually add them. It's clearly something the AWS UI takes care of, which you can do with the API (see additional info) but this module currently does not support. It means you can't really use it to set up a Fargate cluster at all.

### Issue Type

Feature Idea

### Component Name

ecs_cluster

### Additional Information

Enable configuration of ECS cluster capacity providers and strategies thereof.

```yaml
ecs_cluster:
  ...
  capacity_providers:
    - "FARGATE"
    - "FARGATE_SPOT"
  capacity_provider_strategy:
    - capacity_provider: "FARGATE"
      base: 1
      weight: 1
    - capacity_provider: "FARGATE_SPOT"
      weight: 100 
```

hashicorp/terraform-provider-aws#11150
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-capacity-providers.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.put_cluster_capacity_providers

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
>  It means you can't really use it to set up a Fargate cluster at all.

hm I'm not sure about it.  
At work we create some fargate ecs clusters just with

```yml
- name: create ecs cluster
  ecs_cluster:
    name: serverless-housekeeping
    state: present
```

and we can run ecs taskdefinitions with `launch_type: FARGATE` without any problems in that cluster.

```yml
    - name: letsencrypt taskdefinition
      ecs_taskdefinition:
        family: letsencrypt
        cpu: "256"
        memory: "512"
        state: present
        network_mode: awsvpc
        launch_type: FARGATE
        execution_role_arn: "arn:aws:iam::{{ caller_facts.account }}:role/ecsTaskExecutionRole"
        task_role_arn: "arn:aws:iam::{{ caller_facts.account }}:role/letsencryptECSTask"
        region: eu-central-1
        containers:
          - name: letsencrypt
            environment:
              - name: KMS
                value: "{{ kms.ssm }}"
            essential: true
            image: "{{ caller_facts.account }}.dkr.ecr.eu-central-1.amazonaws.com/letsencrypt:latest"
            logConfiguration:
              logDriver: awslogs
              options:
                awslogs-group: /ecs/letsencrypt
                awslogs-region: eu-central-1
                awslogs-stream-prefix: ecs
      register: letsTD
```
