### ISSUE TITLE
add support for gp3 volume throughput setting in ec2_lc

### ISSUE THREAD

**Issue by denizk** [ansible-collections/community.aws#784]
### Summary

The ec2_lc module doesn't seem to support the `throughput` parameter for `gp3` volume types. This parameter is supported by `amazon.aws.ec2_vol`.

### Issue Type

Feature Idea

### Component Name

ec2_lc

### Additional Information

```yaml (paste below)
  - name: Create launch configuration
    community.aws.ec2_lc:
      name: lc1
      image_id: ami-xxxx
      instance_type: t4g.nano
      security_groups: "['sg-xxxx']"
      volumes:
      - device_name: /dev/sda1
        volume_size: 100
        volume_type: gp3
        throughput: 250
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
