### ISSUE TITLE
s3_lifecycle - add  abort_incomplete_multipart_upload and expired_object_delete_marker parameter

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible-collections/community.aws#796]
##### SUMMARY

I would like to apply a bucket lifecycle configuration with `s3_bucket`.

My specific use case is configuring the bucket to abort abandoned multi-part uploads.
(Otherwise you can end up paying for storage of data which is not visible in the bucket.)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
s3_bucket

##### ADDITIONAL INFORMATION

The bucket policy itself is supposed to be xml.

```
- amazon.aws.s3_bucket:
    name: mys3bucket
    state: present
    lifecycle_configuration:
        rules:
        - id: sample-rule</ID>
          status: Enabled
          AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
```

I'm unsure whether the module should use the same capitalisation as the API (`AbortIncompleteMultipartUpload`), or if we should rename to be consistent with Ansible (`abort_incomplete_multipart_upload`) and then convert it.
I suspect using CamelCase would be better.

**Comment by tremble** [comment]
@markuman The slightly confusing thing here is that s3_lifecycle (which manages the lifecycle configuration of s3 buckets) lives in community.aws, whereas s3_bucket (which creates the buckets) lives in amazon.aws.

In my opinion it's better for us to split out some of this configuration as massive monolithic modules become very difficult to properly test, and as such tend to be less reliable, compared to splitting the functionality out.  This becomes even more pronounced when you can apply multiple lifecycle rules based on the folders within a bucket.

At some point Amazon will propably replace boto3 with something incompatible, migrating small modules with well defined scope is *massively* simpler than a monolith that does "all things s3" (see also iam, ec2, etc).

**Comment by markuman** [comment]
Ah oh boy. Blame me. 🙈  
I was confused because the inition post included still `s3_bucket`. [But it's right. as mentioned above, the functionality must be included `s3_lifecycle`](https://github.com/ansible-collections/community.aws/issues/796#issuecomment-947901889)  
So the issue musst moved back to `community.aws`. Sorry :D

**Comment by markuman** [comment]
> If we want the multipart abort to match the API, should we also change expiration to match the API?
> 
> Instead of:
> 
> ```
> expiration_days: 
> expiration_date: 
> expire_object_delete_marker: 
> ```
> 
> It would match more closely if we did:
> 
> ```
> expiration:
>   date:
>   days:
>   expired_object_delete_marker:
> ```
> 
> That requires care to make the change backwards compatible. Currently you can only specify one of these 3 anyway. So should I keep the pattern for `expire` of not matching the API, and add abort in a way that matches the API?

Imo to not break backwards compatibility, it's better to keep the existing structure imo.

**Comment by tremble** [comment]
There's two options:

1) Keep the current structure
2) *Deprecate* the current structure and use something closer to the API

I would actually lean towards 2 as it feels slightly cleaner, but I would be tempted to do something like

```
expiration:
  date:
  days:
  delete_marker: (with an alias of expired_object_delete_marker)
```
