### ISSUE TITLE
Add partition strategy to placement groups module

### ISSUE THREAD

**Issue by hferreira23** [ansible-collections/community.aws#808]
### Summary

Add partition as a strategy for the community.aws.ec2_placement_group module.

Also add an option to choose the actual number of partitions (min 2 which is the default and a max of 7). This option would be taken into account when the strategy is set to partition.

### Issue Type

Feature Idea

### Component Name

ec2_placement_group

### Additional Information

Possible module definition
```yaml (paste below)
- name: Create a Spread placement group.
  community.aws.ec2_placement_group:
    name: my-cluster
    state: present
    strategy: partition
    partition_number: 4
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
