### ISSUE TITLE
ec2_launch_template fails when volume_size is a string

### ISSUE THREAD

**Issue by leedm777** [ansible-collections/community.aws#82]
##### SUMMARY
In some scenarios, the volume_size is being treated as a string instead of an integer. This is causing an "Invalid type" error for that parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_launch_template

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /Users/dlee/prj/cloud-automation/aws-infrastructure/ansible.cfg
  configured module search path = ['/Users/dlee/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dlee/prj/cloud-automation/aws-infrastructure/build/virtualenv/lib/python3.7/site-packages/ansible
  executable location = /Users/dlee/prj/cloud-automation/aws-infrastructure/build/virtualenv/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORCE_HANDLERS(/Users/dlee/prj/cloud-automation/aws-infrastructure/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/dlee/prj/cloud-automation/aws-infrastructure/ansible.cfg) = ['/Users/dlee/prj/cloud-automation/aws-infrastructure/inventory.ini']
DEFAULT_ROLES_PATH(/Users/dlee/prj/cloud-automation/aws-infrastructure/ansible.cfg) = ['/Users/dlee/prj/cloud-automation/aws-infrastructure/build/galaxy']
DEFAULT_STDOUT_CALLBACK(/Users/dlee/prj/cloud-automation/aws-infrastructure/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/Users/dlee/prj/cloud-automation/aws-infrastructure/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS host

##### STEPS TO REPRODUCE

Create a role with the following two tasks, then execute that role.

```yaml
---
- set_fact:
    some_configs:
      - template_name: some-template-1
        volume_size: 10
      - template_name: some-template-2
        volume_size: 20

- name: ec2_launch_template some-template-X
  ec2_launch_template:
    template_name: "{{ item.template_name }}"
    instance_type: t3.nano
    block_device_mappings:
      - device_name: "/dev/sda1"
        ebs:
          volume_size: "{{ item.volume_size | int }}"
          volume_type: gp2
    image_id: ami-068663a3c619dd892
  with_items: "{{ some_configs }}"
```

##### EXPECTED RESULTS

Should create launch template successfully.

##### ACTUAL RESULTS

```paste below
TASK [provision-switchvoxen-recovery-launch-configs : ec2_launch_template some-template-X] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter LaunchTemplateData.BlockDeviceMappings[0].Ebs.VolumeSize, value: 10, type: <class 'str'>, valid types: <class 'int'>
failed: [localhost] (item={'template_name': 'some-template-1', 'volume_size': 10}) => changed=false 
  ansible_loop_var: item
  boto3_version: 1.13.7
  botocore_version: 1.16.7
  item:
    template_name: some-template-1
    volume_size: 10
  msg: |-
    Couldn't create launch template: Parameter validation failed:
    Invalid type for parameter LaunchTemplateData.BlockDeviceMappings[0].Ebs.VolumeSize, value: 10, type: <class 'str'>, valid types: <class 'int'>
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter LaunchTemplateData.BlockDeviceMappings[0].Ebs.VolumeSize, value: 20, type: <class 'str'>, valid types: <class 'int'>
failed: [localhost] (item={'template_name': 'some-template-2', 'volume_size': 20}) => changed=false 
  ansible_loop_var: item
  boto3_version: 1.13.7
  botocore_version: 1.16.7
  item:
    template_name: some-template-2
    volume_size: 20
  msg: |-
    Couldn't create launch template: Parameter validation failed:
    Invalid type for parameter LaunchTemplateData.BlockDeviceMappings[0].Ebs.VolumeSize, value: 20, type: <class 'str'>, valid types: <class 'int'>
```
