### ISSUE TITLE
Use community.aws.rds_instance module to create Aurora cluster

### ISSUE THREAD

**Issue by tonysymbox** [ansible-collections/community.aws#849]
### Summary

I am trying to create an Aurora DB/Cluster from new. I am not clear from the documentation how to do this.

The documentation refers to: "see rds_cluster to manage it" - what does this mean as I do not see any modules for rds_cluster?

Would appreciate your support

Thank you

Tony

### Issue Type

Documentation Report

### Component Name

community.aws.rds_instance

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
Hm, that's a typo in the example section, because there is no `rds_cluster` module.  
Basically you also use `rds_instance` to create a rds "cluster".

But "cluster" is here a buzzword. Because you always create a primary node. always. It does not matter if the engine is mariadb, mysql or aurora.  
After the primary node is deployed. you can attach read replicas to it.

```yml
    - name: add  reader nodes.
      rds_instance:
        engine: aurora-mysql
        db_instance_identifier: "{{ extra_node_name }}"
        instance_type: "{{ extra_node_type }}"
        cluster_id: "{{ cluster }}"
        region: "{{ region }}"
```

The question is, what else do you want to "manage"?  
You can force a failover also with `rds_instance`.   
A snapshot is targeting with `rds_instance_snapshot`.
