### ISSUE TITLE
Add support for setting response header policy id in cache behavior

### ISSUE THREAD

**Issue by ensighten-ekolinko** [ansible-collections/community.aws#877]
### Summary

Add support for setting cache and origin request policy ids in the cache behaviors block when creating a distribution in cloudfront_distribution.

### Issue Type

Feature Idea

### Component Name

cloudfront_distribution

### Additional Information

Currently we are unable to set response header policy ids in the cache behaviors section so that they are added to a cloudfront distribution.

Example playbook code:

      cache_behaviors:
        - path_pattern: "*/"
          target_origin_id: ""
          field_level_encryption_id: ""
          response_headers_policy_id: "{{ response_headers_policy_id }}"

Example python code:

cache_behavior['response_headers_policy_id'] = cache_behavior.get('response_headers_policy_id', config.get('response_headers_policy_id'))
cache_behavior['response_headers_policy_id'] = cache_behavior.get('response_headers_policy_id', config.get('origin_request_policy_id'))

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
This works already :)

```yml
      -
        field_level_encryption_id: ""
        path_pattern: mbmbmbmbmbmbmbmbmbmbmbmbmb-test-wow
        viewer_protocol_policy: "redirect-to-https"
        max_ttl: 31536000
        min_ttl: 0
        default_ttl: 86400
        smooth_streaming: no
        compress: yes
        target_origin_id: Custom-cdn.test.blaaaaaaaaa.de
        response_headers_policy_id: 60669652-455b-4ae9-85a4-c4c02393f86c
        trusted_signers:
          enabled: no
        allowed_methods:
          items:
            - GET
            - HEAD
          cached_methods:
            - GET
            - HEAD
        forwarded_values:
          query_string: true
          cookies:
            forward: all
          headers:
            - "Host"
 ```

The code supports maybe every element in the `cache_behaviour` item. It's just a lack of documentation.
