### ISSUE TITLE
circuit breaker settings missing in ecs_service module

### ISSUE THREAD

**Issue by codedumper1** [ansible-collections/community.aws#921]
### Summary

AWS API provides ability to set deployment configuration for ecs service. Currently ansible module community.aws.ecs_service implements only `maximumPercent` and `minimumHealthyPercent` options but `deploymentCircuitBreaker` is missing. Requesting to add this much needed missing option.

### Issue Type

Feature Idea

### Component Name

community.aws.ecs_service

### Additional Information

as described in https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html yaml should be:
```
ecs_service:
<..>
  deployment_configuration:
    minimum_percent: x
    minimum_healthy_percent: y
    deploymentCircuitBreaker:
      enabled: yes
      rollback: yes
```
JSON syntax:
```
"deployment_configuration": {
  "deploymentCircuitBreaker": {
    "enable": true|false,
    "rollback": true|false
  },
  "maximumPercent": integer,
  "minimumHealthyPercent": integer
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/ecs_service.py`](https://github.com/['ansible-collections/amazon.aws', 'ansible-collections/community.aws', 'ansible-collections/community.vmware']/blob/main/plugins/modules/ecs_service.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Java1Guy @jillr @kaczynskid @markuman @s-hertel @tremble @zacblazic
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by karcadia** [comment]
This already works as an undocumented feature. I can add the documentation and examples.

Then maybe we just add ```'deployment_circuit_breaker': 'dict'``` to this https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/ecs_service.py#L486 and I think that's it? Do you see anything else?

Working example:
```
- name: Build an ECS service.
      community.aws.ecs_service:
        state: "present"
        region: "{{ AWS_REGION }}"
        validate_certs: False
        aws_access_key: "{{ survey_access_key_id }}"
        aws_secret_key: "{{ survey_secret_access_key }}"
        aws_security_token: "{{ survey_session_token }}"
        name: service2
        cluster: my_cluster_name
        task_definition: my-task-def
        desired_count: 1
        launch_type: FARGATE
        network_configuration:
          assign_public_ip: no
          security_groups:
            - sg-abcd
          subnets:
            - subnet-1
            - subnet-2
            - subnet-3
            - subnet-4
        deployment_configuration:
          minimum_healthy_percent: 1
          deployment_circuit_breaker:
            enable: True
            rollback: True
```
