### ISSUE TITLE
ec2_asg when replacing instances, support terminating prior to bring up new instances

### ISSUE THREAD

**Issue by anjo-swe** [ansible-collections/community.aws#931]
### Summary

When updating the version some services it's recommended to terminate the old instance(s) prior to starting up new ones. 

Currently when `ec2_asg` replaces instances it first increases the min / desired / max sizes on the ASG by the batch size. By using `terminate_before_replace` it would leave the ASG sizes the same and then terminate X instances (based on batch size) at the time and wait for new instances to come up.

### Issue Type

Feature Idea

### Component Name

ec2_asg

### Additional Information

```yaml (paste below)
- community.aws.ec2_asg:
    name: my_asg
    launch_config_name: my_lc
    health_check_period: 60
    health_check_type: ELB
    terminate_before_replace: yes
    replace_all_instances: yes
    min_size: 5
    max_size: 5
    desired_capacity: 5
    region: us-east-1
```

`terminate_before_replace` would be used together with `replace_all_instances` or `replace_instances`

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
