### ISSUE TITLE
Global Accelerator Modules

### ISSUE THREAD

**Issue by TylerLubeck** [ansible-collections/community.aws#94]
##### SUMMARY
I'd like to be able to manage [AWS Global Accelerators](https://aws.amazon.com/global-accelerator/) with ansible

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- `list_global_accelerators`
- `global_accelerator_listener`
- `global_accelerator_endpoint_group`
- `global_accelerator`

I'm bad at names

##### ADDITIONAL INFORMATION

```yaml
- name: List Global Accelerators
   list_global_accelerators:
     region: us-west-2
   register: accelerators

- name: Print Global Accelerator DNS
   debug:
     msg: "{{ item.dns_name }}"
   loop: "{{ accelerators.accelerators }}"

# https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html
- name: Ensure Global Accelerator Exists
   global_accelerator:
     enabled: true
     name: my_accelerator
     tags:
        application: testing
   register: my_accelerator

# https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateListener.html
- name: Ensure Global Accelerator Listener exists
   global_accelerator_listener:
     accelerator_arn: "{{ my_accelerator.accelerator_arn }}"
     client_affinity: no
     protocol: tcp
     port_ranges:
       - low: 80
          high: 80
  register: my_listener

# https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateEndpointGroup.html     
- name: Ensure Global Accelerator Endpoint Group exists
   global_accelerator_endpoint_group:
     endpoint_configurations:
        - ip_preservation: true
           endpoint_id: i-12345abcd # EC2 Instance ID
           weight: 1
        region: us-east-1
        health_check_interval: 2
        health_check_path: /healthcheck
        health_check_port: 80
        listener_arn: "{{ my_listener.listener_arn }}"
        threshold_count: 3
        traffic_percentage: 100
   register: my_endpoint_group
```
