### ISSUE TITLE
sns_topic: tagging support

### ISSUE THREAD

**Issue by dtnyn** [ansible-collections/community.aws#964]
### Summary

sns_topic doesn't not currently support resources tagging. It should have a `tags` parameter for AWS tags

### Issue Type

Feature Idea

### Component Name

sns_topic

### Additional Information

This issue was previously raised in the main ansible repo https://github.com/ansible/ansible/issues/65613 before the community migration but doesn't seems like it was raised here. There was also a PR for the issue https://github.com/ansible/ansible/pull/68287.

Similar to the previous proposal, I would like the ability to add tags dict as a parameter similar to `s3_bucket` and `ec2`

```yaml
-  sns_topic:
    name: "alarms"
    state: present
    tags:
     Environment: Production
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
