### ISSUE TITLE
List of modules without integration tests

### ISSUE THREAD

**Issue by alinabuzachis** [ansible-collections/community.aws#988]
### Summary

The following modules do not have integrations tests:

- [ ]  aws_application_scaling_policy
- [ ] aws_batch_compute_environment
- [ ] aws_batch_job_definition
- [ ] aws_batch_job_queue
- [ ] aws_direct_connect_confirm_connection
- [ ] aws_direct_connect_connection
- [ ] aws_direct_connect_gateway
- [ ] aws_direct_connect_link_aggregation_group
- [ ] aws_direct_connect_virtual_interface
- [ ] aws_s3_cors
- [ ] aws_sgw_info
- [ ] cloudfront_info
- [ ] cloudfront_invalidation
- [ ] cloudfront_origin_access_identity
- [ ] cloudwatchevent_rule
- [ ] cloudwatchlogs_log_group_info
- [ ] data_pipeline
- [ ] dynamodb_ttl
- [ ] ec2_ami_copy
- [ ] ec2_asg_lifecycle_hook
- [ ] ec2_customer_gateway
- [ ] ec2_customer_gateway_info
- [ ] ec2_snapshot_copy
- [ ] ec2_vpc_vgw_info
- [ ] ec2_win_password
- [ ] ecs_attribute
- [ ] elasticache_info
- [ ] elasticache_parameter_group
- [ ] elasticache_snapshot
- [ ] elb_target_group_info
- [ ] iam_mfa_device_info
- [ ] lambda_event
- [ ] rds_instance_snapshot
- [ ] rds_snapshot_info
- [ ] redshift_cross_region_snapshots
- [ ] s3_website
- [ ] sts_session_token
- [ ] ec2_vpc_vpn 

### Issue Type

Feature Idea

### Component Name

Several modules

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by marknet15** [comment]
`*_infra` can be linked to the non info counterparts on most occasions I think, so that shouldn't be too hard to cover

**Comment by alinabuzachis** [comment]
@marknet15 Yes, exactly. At the moment, I didn't link them because the _info modules were not really used by the non info counterparts. I think we should have a couple of tasks using the _info module at least.

**Comment by markuman** [comment]
>  aws_sgw_info

this is a very hard one, because there is no module to create a storage gateway yet.

**Comment by markuman** [comment]
> > aws_sgw_info
> 
> this is a very hard one, because there is no module to create a storage gateway yet.

a few words more about the storage gateway (_sgw_).  

To deploy a storage gateway, you'll need to deploy an EC2 instance with a special ami. easy.  
Now it comes to the registration process. This is how we handle this.

```yml
- name: init sgw
  block:

    - name: get activation code
      uri:
        url: "http://{{ sgw_instance.instances[0].private_ip_address }}/?activationRegion={{ region }}"
        method: GET
        return_content: yes
      register: ACTICATION_TOKEN
      retries: 10
      delay: 30
      until: ACTICATION_TOKEN is not failed

    - name: register new sgw
      command: aws storagegateway activate-gateway \
        --activation-key {{ ACTICATION_TOKEN.url.split('activationKey=')[-1] }} \
        --gateway-name {{ sgw_name }} \
        --gateway-timezone GMT+1:00 \
        --gateway-region {{ region }} \
        --gateway-type FILE_S3

    - name: "list sgw: retries until gateway_operational_state is connected"
      aws_sgw_info:
        region: "{{ region }}"
        gather_file_shares: yes
        gather_local_disks: yes
        gather_tapes: no
        gather_volumes: no
      register: sgwfacts
      retries: 10
      delay: 30
      until: sgwfacts is not failed
```

After the instance has bootet, it took 1-3 minutes until you can curl the registration code. For this the node that runs the integration test must be

* integrated in  the VPC (_in case of working with private ip_)
* **or** the EC2 instance needs a public IP where port 80 is available for the integration test node


To archive idempotent here, this block is only executed if the sgw isn't connected/available already

```yml
- name: list sgw
  aws_sgw_info:
    region: "{{ region }}"
    gather_file_shares: yes
    gather_local_disks: yes
    gather_tapes: no
    gather_volumes: no
  register: sgwfacts

- name: merge sgw names
  set_fact:
    sgws: "{{ sgwfacts.gateways |  map(attribute='gateway_name') | list }}"

- include_tasks: init_sgw.yml
  when: sgw_name not in sgws
```

So at the end, to test `aws_sgw_info` module, we'll need at least a `sgw_activate_gateway` (_or some similar name, when it should also be used to delete the sgw_) module, where this modules include also fetch of the registration code

```yml
- community.aws.sgw_activate_gateway:
    name: "{{ sgw_name }}"
    state: ['present','absent']
    ip: 1.2.3.4
```

...but it's also possible to glue everything with other modules together 😎
